import React from "react";
import { Link } from 'react-router-dom'

function Downloadbtn(props) {
	return <a href={props.to} style={{ marginRight: '05px' }}><button className={props.color} style={{ marginBottom: '05px' }}>Download<br /><small><i>{props.Version}</i></small></button></a>
}

function Nootherversion() {
	return (
		<p>
			<i>No older version is Available</i>
		</p>
	);
}

function V(props) {
	return <h5><i>{props.v}</i></h5>
}

let Data = [
	{
		Name: "Avast Antivirus",
		img: "/media/images/100x100/antivirus/avast.jpg",
		To: "/categories/antivirus/avast",
		Categories: "Antivirus",
		Windows: "Windows",
		Apps: "Apps",
		olderversions: Nootherversion(),
		filename: "avast_free_antivirus_setup_windows_online for Windows, Avast Antivirus Mobile for Andoroid",
		setupsize: "< 1MB for Windows, 30MB for Android",
		Free: "Free",
		dev: "Avast",
		devhref: "https://www.avast.com/en-in/",
		sysos: "Android or Windows 7, 8.1, 10",
		sysram: "> 2GB",
		type: "Online Installer",
		sysarch: '×64, ×32',
		desc: "Avast Antivirus is a family of cross-platform internet security applications developed by Avast for Microsoft Windows, macOS, Android and iOS",
		Download: <div><V v="v6" /><span className="mb-3"><Downloadbtn className="mb-3" to="https://get-softwares.github.io/avast/Avast-Antivirus Mobile.xapk" color="btn btn-primary" Version="Android" /></span><Downloadbtn to='https://get-softwares.github.io/avast/avast_free_antivirus_setup_windows_online.exe' className="mb-3" color="btn btn-primary" Version="Windows" /></div>

	},
	{
		Name: "AVG Antivirus",
		img: "/media/images/100x100/antivirus/avg.jpg",
		To: "/categories/antivirus/avg",
		Categories: "Antivirus",
		Windows: "Windows",
		Apps: "Apps",
		desc: "AVG Antivirus is a cross-platform internet security applications developed by AVG to prevent viruses from the computer",
		olderversions: Nootherversion(),
		filename: "avg_antivirus_offline for Windows, avg_antivirus for Android",
		setupsize: "550MB for Windows, 40MB for Android",
		Free: "Trial",
		dev: "AVG",
		devhref: "https://www.avg.com/en-in/",
		sysos: "Android or Windows 7, 8.1, 10",
		sysram: "> 2GB",
		type: "Online Installer",
		sysarch: '×64, ×32',
		Download: <div><span className="mb-3"><Downloadbtn className="mb-3" to="https://get-softwares.github.io/avg/AVG-AntiVirus-2021 Free-Mobile-Security.apk" color="btn btn-primary" Version="Android" /></span><Downloadbtn to='https://www.avg.com/en-in/download-thank-you.php?product=FREEGSR-OFFLINE' className="mb-3" color="btn btn-primary" Version="Windows" /></div>
	},
	{
		Name: "Avira Antivirus",
		img: "/media/images/100x100/antivirus/avira.jpg",
		To: "/categories/antivirus/avira",
		Categories: "Antivirus",
		Windows: "Windows",
		Apps: "",
		desc: "Avira Operations GmbH & Co. KG is a German multinational computer security software company mainly known for their antivirus software Avira Free Security.",
		olderversions: Nootherversion(),
		filename: "avira_en",
		setupsize: "4MB",
		Free: "Free",
		dev: "Avira",
		devhref: "https://www.avira.com/",
		sysos: "Windows 7, 8.1, 10",
		sysram: "> 2GB",
		type: "Online Installer",
		sysarch: '×64, ×32',
		Download: <div><Downloadbtn to='https://get-softwares.github.io/avira/avira_en.exe' className="mb-3" color="btn btn-primary" Version="Windows" /></div>
	},
	{
		Name: "Avant Browser",
		img: "/media/images/100x100/browser/Avant-Browser.jpg",
		To: "/categories/browser/avant-browser",
		Categories: "Browser",
		Windows: "Windows",
		Apps: "",
		desc: "Avant Browser is a freeware web browser from a Chinese programmer named Anderson Che, which unites the Trident layout engine built into Windows (see Internet Explorer shell) with an interface intended to be more feature-rich, flexible and ergonomic than Microsoft 's Internet Explorer (IE).",
		olderversions: Nootherversion(),
		filename: "asetup.exe",
		setupsize: "111MB",
		Free: "Free",
		dev: "Avant",
		devhref: "http://www.avantbrowser.com/",
		sysos: "Windows 7, 8.1, 10",
		sysram: " 4GB",
		type: "Offline Installer",
		sysarch: '×64, ×32',
		Download: <div><Downloadbtn to='http://dl1.avantbrowser.com/asetup.exe' className="mb-3" color="btn btn-primary" Version="Windows" /></div>
	},
	{
		Name: "Avast Secure Browser",
		img: "/media/images/100x100/browser/avastsecurebrowser.png",
		To: "/categories/browser/avast-secure-browser",
		Categories: "Browser",
		Windows: "Windows",
		Apps: "Apps",
		desc: "Avast Secure Browser is the secure browser developed by Avast for more security in browsing the internet.",
		olderversions: Nootherversion(),
		filename: "avast_secure_browser_setup for Windows, Avast-Secure-Browser-Mobile for Andorid",
		setupsize: "3MB for Windows, 73MB for Android",
		Free: "Free",
		dev: "Avast",
		devhref: "https://www.avast.com/en-in/",
		sysos: "Android, Windows 7, 8.1, 10",
		sysram: " 4GB",
		type: "Offline Installer",
		sysarch: '×64, ×32',
		Download: <div><Downloadbtn to='https://get-softwares.github.io/avast-secure-browser/avast_secure_browser_setup.exe' className="mb-3" color="btn btn-primary" Version="Windows" /><Downloadbtn to='https://get-softwares.github.io/avast-secure-browser/Avast-Secure-Browser-Mobile.apk' className="mb-3" color="btn btn-primary" Version="Android" /></div>
	},
	{
		Name: "AVG Secure Browser",
		img: "/media/images/100x100/browser/avgsecurebrowser.png",
		To: "/categories/browser/avg-secure-browser",
		Categories: "Browser",
		Windows: "Windows",
		Apps: "Apps",
		desc: "AVG Secure Browser is the secure browser developed by AVG for more security in browsing the internet.",
		olderversions: Nootherversion(),
		filename: "avast_secure_browser_setup for Windows, AVG-Browser-Mobile for Andorid",
		setupsize: "3MB for Windows, 62MB for Android",
		Free: "Free",
		dev: "AVG",
		devhref: "https://www.avg.com/en-in/",
		sysos: "Android, Windows 7, 8.1, 10",
		sysram: " 4GB",
		type: "Offline Installer for Android, Online Installer for Windows",
		sysarch: '×64, ×32',
		Download: <div><Downloadbtn to='https://get-softwares.github.io/avg-secure-browser/avg_secure_browser_setup.exe' className="mb-3" color="btn btn-primary" Version="Windows" /><Downloadbtn to='https://get-softwares.github.io/avg-secure-browser/AVG-Browser-Mobile.apk' className="mb-3" color="btn btn-primary" Version="Android" /></div>
	},
	{
		Name: "Brave Browser",
		img: "/media/images/100x100/browser/brave.png",
		To: "/categories/browser/brave",
		Categories: "Browser",
		Windows: "Windows",
		Apps: "Apps",
		desc: "Brave is a free and open-source web browser developed by Brave Software, Inc. based on the Chromium web browser.",
		olderversions: Nootherversion(),
		filename: "braveBrowserSetup for ×64, braveBrowserSetupx32 for ×32, braveBrowserSetupMobile for Android",
		setupsize: "2MB for Windows, 170MB for Android",
		Free: "Free",
		dev: "Brave",
		devhref: "https://brave.com/",
		sysos: "Android, Windows 7, 8.1, 10",
		sysram: " 4GB",
		type: "Online Installer for Windows, Offline Installer for Android",
		sysarch: '×64, ×32',
		Download: <div><Downloadbtn to='https://get-softwares.github.io/brave/BraveBrowserSetup.exe' className="mb-3" color="btn btn-primary" Version="&times;64 Windows" /><Downloadbtn to='https://get-softwares.github.io/brave/BraveBrowserSetup32.exe' className="mb-3" color="btn btn-primary" Version="&times;32 Windows" /><Downloadbtn to='https://get-softwares.github.io/brave/Brave_Browser.zip' className="mb-3" color="btn btn-primary" Version="Android" /></div>
	},
	{
		Name: "Cent",
		img: "/media/images/100x100/browser/cent.png",
		To: "/categories/browser/cent",
		Categories: "Browser",
		Windows: "Windows",
		Apps: "",
		desc: "Cent Browser is based on Chromium, and it's designed as a privacy-focused Chrome alternative.",
		olderversions: Nootherversion(),
		filename: "CentBrowserSetup",
		setupsize: "75MB",
		Free: "Free",
		dev: "Cent",
		devhref: "https://www.centbrowser.com/",
		sysos: "Windows 7, 8.1, 10",
		sysram: " 4GB",
		type: "Online Installer for Windows, Offline Installer for Android",
		sysarch: '×64, ×32',
		Download: <div><Downloadbtn to='https://get-softwares.github.io/cent/centbrowser.exe' className="mb-3" color="btn btn-primary" Version="Windows" /></div>
	},
	{
		Name: "Google Chrome",
		img: "/media/images/100x100/browser/chrome.png",
		To: "/categories/browser/chrome",
		Categories: "Browser",
		Windows: "Windows",
		Apps: "Apps",
		desc: "Google Chrome is a cross-platform web browser developed by Google. And a Great Browser for Windows and Android.",
		olderversions: Nootherversion(),
		filename: "86_chrome_setup for Windows, Google_Chrome_Mobile for Android",
		setupsize: "90MB for Windows, 142MB for Android",
		Free: "Free",
		dev: "Chrome",
		devhref: "https://www.google.com/chrome/",
		sysos: "Android, Windows 7, 8.1, 10",
		sysram: " 4GB",
		type: "Offline Installer",
		sysarch: '×64, ×32',
		Download: <div><Downloadbtn to='https://get-softwares.github.io/chrome/chrome_installer_x64.exe' className="mb-3" color="btn btn-primary" Version="&times;64 Windows" /><Downloadbtn to='https://get-softwares.github.io/chrome/chrome_installer_x32.exe' className="mb-3" color="btn btn-primary" Version="&times;32 Windows" /><Downloadbtn to='https://get-softwares.github.io/chrome/Google Chrome Mobile.zip' className="mb-3" color="btn btn-primary" Version="Android" /></div>
	},
	{
		Name: "Firefox",
		img: "/media/images/100x100/browser/firefox.jpg",
		To: "/categories/browser/firefox",
		Categories: "Browser",
		Windows: "Windows",
		Apps: "Apps",
		desc: "Firefox Browser, also known as Mozilla Firefox or simply Firefox, is a free and open-source web browser developed by the Mozilla Foundation and its subsidiary, the Mozilla Corporation.",
		olderversions: Nootherversion(),
		filename: "Firefox Setup 83.0 for Windows, FIrefox_Web_Browser_Mobile for Android",
		setupsize: "55MB for Windows, 72MB for Android",
		Free: "Free",
		dev: "Firfox",
		devhref: "https://www.mozilla.org/",
		sysos: "Android, Windows 7, 8.1, 10",
		sysram: " 4GB",
		type: "Offline Installer",
		sysarch: '×64, ×32',
		Download: <div><Downloadbtn to='https://get-softwares.github.io/firefox/Firefox Setup 83.0-x64.exe' className="mb-3" color="btn btn-primary" Version="&times;64 Windows" /><Downloadbtn to='https://get-softwares.github.io/firefox/Firefox Setup 83.0-x32.exe' className="mb-3" color="btn btn-primary" Version="&times;32 Windows" /><Downloadbtn to='https://get-softwares.github.io/firefox/Firefox-Browser-Mobile.apk' className="mb-3" color="btn btn-primary" Version="Android" /></div>
	},
	{
		Name: "Maxthon",
		img: "/media/images/100x100/browser/maxathon.png",
		To: "/categories/browser/maxathon",
		Categories: "Browser",
		Windows: "Windows",
		Apps: "",
		desc: "Maxthon is a cloud browser and it uses a remote server, unlike other browsers which use public server. This makes a huge difference when it comes to server security.",
		olderversions: Nootherversion(),
		filename: "maxthon_×32 for ×32 Windows, maxthon_x64 for x64 Windows",
		setupsize: "86MB",
		Free: "Free",
		dev: "Maxthon",
		devhref: "https://www.maxthon.com/",
		sysos: "Windows 7, 8.1, 10",
		sysram: " 4GB",
		type: "Offline Installer",
		sysarch: '×64, ×32',
		Download: <div><Downloadbtn to='https://get-softwares.github.io/maxthon/maxthon_x64.exe' className="mb-3" color="btn btn-primary" Version="&times;64 Windows" /><Downloadbtn to='https://get-softwares.github.io/maxthon/maxthon_x32.exe' className="mb-3" color="btn btn-primary" Version="&times;32 Windows" /></div>
	},
	{
		Name: "Microsoft Edge",
		img: "/media/images/100x100/browser/edge.jpg",
		To: "/categories/browser/edge",
		Categories: "Browser",
		Windows: "Windows",
		Apps: "Apps",
		desc: "Microsoft Edge is a cross-platform web browser developed by Microsoft. It is a chromium based browser.",
		olderversions: Nootherversion(),
		filename: "edge_setup for Windows, Microsoft_Edge_Web_Browser_Mobile for Android",
		setupsize: "1.7MB for Windows, 90MB for Android",
		Free: "Free",
		dev: "Microsoft",
		devhref: "https://www.microsoft.com/en-us/edge",
		sysos: "Android, Windows 7, 8.1, 10",
		sysram: " 4GB",
		type: "Offline Installer for Android, Online Installer for Windows",
		sysarch: '×64, ×32',
		Download: <div><Downloadbtn to='https://get-softwares.github.io/edge/MicrosoftEdgeSetup.exe' className="mb-3" color="btn btn-primary" Version="Windows" /><Downloadbtn to='https://get-softwares.github.io/edge/Microsoft-Edge-Web-Browser-Mobile.apk' className="mb-3" color="btn btn-primary" Version="Android" /></div>
	},
	{
		Name: "Opera",
		img: "/media/images/100x100/browser/opera.jpg",
		To: "/categories/browser/opera",
		Categories: "Browser",
		Windows: "Windows",
		Apps: "Apps",
		desc: "Opera is a Chromium-based browser. It distinguishes itself from other browsers through its user interface, functionality, and other features. Opera was initially released in April 1995, making it one of the oldest desktop web browsers still actively developed today.",
		olderversions: Nootherversion(),
		filename: "Opera_Setup 83.0, opera_Setup_Mobile for Android",
		setupsize: "55MB for Windows, 75MB for Android",
		Free: "Free",
		dev: "Opera",
		devhref: "https://www.opera.com/",
		sysos: "Android, Windows 7, 8.1, 10",
		sysram: " 4GB",
		type: "Offline Installer",
		sysarch: '×64, ×32',
		Download: <div><Downloadbtn to='https://get-softwares.github.io/opera/Opera_Setup.exe' className="mb-3" color="btn btn-primary" Version="Windows" /><Downloadbtn to='https://get-softwares.github.io/opera/Opera-Browser.apk' className="mb-3" color="btn btn-primary" Version="Android" /></div>
	},
	{
		Name: "Torch",
		img: "/media/images/100x100/browser/torch.png",
		To: "/categories/browser/torch",
		Categories: "Browser",
		Windows: "Windows",
		Apps: "",
		desc: "Torch is a Chromium-based web browser and Internet suite developed by the North Carolina based Torch Media. The browser handles common Internet-related tasks such as displaying websites, sharing websites via social networks, downloading torrents, accelerating downloads and grabbing online media, all directly from the browser. Torch Browser is commercial freeware.",
		olderversions: Nootherversion(),
		filename: "Torch_Web_Browser",
		setupsize: "1MB",
		Free: "Free",
		dev: "Torch",
		devhref: "https://torchbrowser.com/",
		sysos: "Windows 7, 8.1, 10",
		sysram: " 4GB",
		type: "Online Installer",
		sysarch: '×64, ×32',
		Download: <div><Downloadbtn to='https://torchbrowser.com/' className="mb-3" color="btn btn-primary" Version="Windows" /></div>
	},
	{
		Name: "Vivaldi",
		img: "/media/images/100x100/browser/vivaldi.png",
		To: "/categories/browser/vivaldi",
		Categories: "Browser",
		Windows: "Windows",
		Apps: "",
		desc: "Vivaldi is a freeware, cross-platform web browser developed by Vivaldi Technologies, a company founded by Tatsuki Tomita and Jon Stephenson von Tetzchner, who was the co-founder and CEO of Opera Software.",
		olderversions: Nootherversion(),
		filename: "Vivaldi_Setup",
		setupsize: "60MB",
		Free: "Free",
		dev: "Vivaldi",
		devhref: "https://vivaldi.com/",
		sysos: "Windows 7, 8.1, 10",
		sysram: " 4GB",
		type: "Offline Installer",
		sysarch: '×64, ×32',
		Download: <div><Downloadbtn to='https://get-softwares.github.io/vivaldi/Vivaldi_Setup.exe' className="mb-3" color="btn btn-primary" Version="Windows" /></div>
	},
	{
		Name: "Eagle Get",
		img: "/media/images/100x100/dmanager/eagleget.png",
		To: "/categories/download-manager/eagle-get",
		Categories: "Download Manager",
		Windows: "Windows",
		Apps: "",
		desc: "EagleGet is a free all-in-one download manager and accelerator. The EagleGet Downloader extension for Edge could take over and accelerate the downloads from your browser.",
		olderversions: Nootherversion(),
		filename: "eagleget_setup",
		setupsize: "10MB",
		Free: "Free",
		dev: "Eagleget",
		devhref: "http://www.eagleget.com/download/",
		sysos: "Windows 7, 8.1, 10",
		sysram: " 2GB",
		type: "Offline Installer",
		sysarch: '×64, ×32',
		Download: <div><Downloadbtn to='https://get-softwares.github.io/eagle-get/eagleget_setup.exe' className="mb-3" color="btn btn-primary" Version="Windows" /></div>
	},
	{
		Name: "FDM",
		img: "/media/images/100x100/dmanager/fdm.jpg",
		To: "/categories/download-manager/fdm",
		Categories: "Download Manager",
		Windows: "Windows",
		Apps: "",
		desc: "Free Download Manager (FDM) is the download manager to download big files or torrent with speed and with pause and unpause the files or torrent file",
		olderversions: Nootherversion(),
		filename: "fdm_setup",
		setupsize: "30MB",
		Free: "Free",
		dev: "FDM",
		devhref: "https://www.freedownloadmanager.org/",
		sysos: "Windows 7, 8.1, 10",
		sysram: " 2GB",
		type: "Online Installer",
		sysarch: '×64, ×32',
		Download: <div><Downloadbtn to='https://get-softwares.github.io/fdm/fdm_x32_setup.exe' className="mb-3" color="btn btn-primary" Version="&times;32 Windows" /><Downloadbtn to='https://get-softwares.github.io/fdm/fdm_x64_setup.exe' className="mb-3" color="btn btn-primary" Version="&times;64 Windows" /></div>
	},
	{
		Name: "IDM",
		img: "/media/images/100x100/dmanager/idm.png",
		To: "/categories/download-manager/idm",
		Categories: "Download Manager",
		Windows: "Windows",
		Apps: "",
		desc: "Internet Download Manager (IDM) is a tool to increase download speeds by up to 5 times, resume and schedule downloads. Comprehensive error recovery and resume capability will restart broken or interrupted downloads due to lost connections, network problems, computer shutdowns, or unexpected power outages.",
		olderversions: Nootherversion(),
		filename: "idman638build3",
		setupsize: "15MB",
		Free: "Trial",
		dev: "IDM",
		devhref: "https://www.internetdownloadmanager.com/",
		sysos: "Windows 7, 8.1, 10",
		sysram: " 2GB",
		type: "Offline Installer",
		sysarch: '×64, ×32',
		Download: <div><Downloadbtn to='https://get-softwares.github.io/idm/idmSetup.exe' className="mb-3" color="btn btn-primary" Version="Windows" /></div>
	},
	{
		Name: "JDownloader",
		img: "/media/images/100x100/dmanager/jdownloader.webp",
		To: "/categories/download-manager/j-downloader",
		Categories: "Download Manager",
		Windows: "Windows",
		Apps: "",
		desc: "JDownloader is a free, open-source download management tool with a huge community of developers that makes downloading as easy and fast as it should be. Users can start, stop or pause downloads, set bandwith limitations, auto-extract archives and much more. It's an easy-to-extend framework that can save hours of your valuable time every day.",
		olderversions: Nootherversion(),
		filename: "jdownloader_setup",
		setupsize: "50MB",
		Free: "Free",
		dev: "JDownloader",
		devhref: "https://jdownloader.org/",
		sysos: "Windows 7, 8.1, 10",
		sysram: " 2GB",
		type: "Online Installer",
		sysarch: '×64, ×32',
		Download: <div><Downloadbtn to='https://get-softwares.github.io/j-downloader/JDownloaderSetup-x32-x64.exe' className="mb-3" color="btn btn-primary" Version="Windows" /></div>
	},
	{
		Name: "Andy",
		img: "/media/images/100x100/Emulators/Andy.jpg",
		To: "/categories/emulators/andy",
		Categories: "Emulators",
		Windows: "Windows",
		Apps: "",
		desc: "Andy, or 'Andy the Android Emulator' allows you to utilize your Android applications, like WhatsApp or Snapchat, through your Windows PC or Mac desktop.",
		olderversions: Nootherversion(),
		filename: "Andy_47.260_1096_26_x64",
		setupsize: "4MB",
		Free: "Free",
		dev: "Andy",
		devhref: "https://www.andyroid.net/",
		sysos: "Windows 7, 8.1, 10",
		sysram: " 4GB",
		type: "Online Installer",
		sysarch: '×64',
		Download: <div><V v="v47" /><Downloadbtn to='https://get-softwares.github.io/andy/Andy_47.260_1096_26_x64.exe' className="mb-3" color="btn btn-primary" Version="&times;64 Windows" /></div>
	},
	{
		Name: "Bluestacks",
		img: "/media/images/100x100/Emulators/bluestacks.png",
		To: "/categories/emulators/bluestacks",
		Categories: "Emulators",
		Windows: "Windows",
		Apps: "",
		desc: "BlueStacks is an American technology company that produces the BlueStacks App Player and other cloud-based cross-platform products. The BlueStacks App Player is designed to enable Android applications to run on PCs running Microsoft Windows and Apple's macOS.",
		olderversions: Nootherversion(),
		filename: "Bluestacks 5 for Bluestacks 5, Bluestacks 4 for Bluestacks 4",
		setupsize: "2MB for Bluestacks 5 beta, 450 MB for Bluestacks 4",
		Free: "Free",
		dev: "Bluestacks",
		devhref: "https://www.bluestacks.com/",
		sysos: "Windows 7, 8.1, 10",
		sysram: " 4GB",
		type: "Online Installer for Bluestacks 5, Offline Installer for Bluestacks 4",
		sysarch: '×64 ×32',
		Download: <div><V v="v5 Beta" /><Downloadbtn to='https://get-softwares.github.io/bluestacks/BlueStacks-5-Installer.exe' className="mb-3" color="btn btn-primary" Version="Windows" /><V v='v4' /><Downloadbtn to='https://cloud.bluestacks.com/get_offline_download?os_arch=x64' className="mb-3" color="btn btn-primary" Version="&times;32 Windows" /><Downloadbtn to='https://cloud.bluestacks.com/get_offline_download?os_arch=x86' className="mb-3" color="btn btn-primary" Version="&times;64 Windows" /></div>
	},
	{
		Name: "GameLoop",
		img: "/media/images/100x100/Emulators/gameloop.jpg",
		To: "/categories/emulators/gameloop",
		Categories: "Emulators",
		Windows: "Windows",
		Apps: "",
		desc: "Gameloop is the emulator developed by Tencent Gaming, the company that developed the mobile version of one of the popular battle royal games. Gameloop does not contain any type of Viruses, Malware, and Spyware.",
		olderversions: Nootherversion(),
		filename: "Gameloop_Download_SpecialPackage",
		setupsize: "7MB",
		Free: "Free",
		dev: "Gameloop",
		devhref: "https://www.gameloop.com",
		sysos: "Windows 7, 8.1, 10",
		sysram: " 4GB",
		type: "Online Installer",
		sysarch: '×64',
		Download: <div><V v="v5 Beta" /><Downloadbtn to='https://get-softwares.github.io/gameloop/Gameloop_Download_SpecialPackage.exe' className="mb-3" color="btn btn-primary" Version="Windows" /></div>
	},
	{
		Name: "Genymotion",
		img: "/media/images/100x100/Emulators/genymotion.png",
		To: "/categories/emulators/genymotion",
		Categories: "Emulators",
		Windows: "Windows",
		Apps: "",
		desc: "Genymotion is a complete Android emulator for Windows. It's very powerful and easy to use even for casual users, who shouldn't have any problem navigating and controlling the program.",
		olderversions: Nootherversion(),
		filename: "Genymotion",
		setupsize: "140MB",
		Free: "License",
		dev: "Genymotion",
		devhref: "https://www.genymotion.com/",
		sysos: "Windows 7, 8.1, 10",
		sysram: " 4GB",
		type: "Online Installer",
		sysarch: '×64',
		Download: <div><Downloadbtn to='https://www.dropbox.com/s/n8igkrj2dwl6hmr/genymotion-3.2.0.exe?dl=1' className="mb-3" color="btn btn-primary" Version="Windows" /></div>
	},
	{
		Name: "KO Player",
		img: "/media/images/100x100/Emulators/koplayer.jpg",
		To: "/categories/emulators/ko-player",
		Categories: "Emulators",
		Windows: "Windows",
		Apps: "",
		desc: "KO Player is an Android emulator for gamers, running Android App. It features the usual array of gamer-oriented features, including good keyboard mapping controls, multi-instance, macros, high FPS, and graphical support.",
		olderversions: Nootherversion(),
		filename: "koplayer-2.0.0",
		setupsize: "603MB",
		Free: "Free",
		dev: "KO player",
		devhref: "https://koplayerpc.com/",
		sysos: "Windows 7, 8.1, 10",
		sysram: " 4GB",
		type: "Offline Installer",
		sysarch: '×64',
		Download: <div><Downloadbtn to='https://lon-01.lo4d.com/files/koplayer/koplayer-2.0.0.exe' className="mb-3" color="btn btn-primary" Version="Windows" /></div>
	},
	{
		Name: "LD Player",
		img: "/media/images/100x100/Emulators/ldplayer.jpg",
		To: "/categories/emulators/ldplayer",
		Categories: "Emulators",
		Windows: "Windows",
		Apps: "",
		desc: "LDPlayer is an Android emulator for gamers, running Android Nougat 7.1. It features the usual array of gamer-oriented features, including good keyboard mapping controls, multi-instance, macros, high FPS, and graphical support.",
		olderversions: Nootherversion(),
		filename: "LDPlayer4",
		setupsize: "3MB",
		Free: "Free",
		dev: "LD player",
		devhref: "https://www.ldplayer.net/",
		sysos: "Windows 7, 8.1, 10",
		sysram: " 4GB",
		type: "Online Installer",
		sysarch: '×32, ×64',
		Download: <div><Downloadbtn to='https://get-softwares.github.io/ld-player/LDPlayer4.exe' className="mb-3" color="btn btn-primary" Version="Windows" /></div>
	},
	{
		Name: "Memu",
		img: "/media/images/100x100/Emulators/memu.jpg",
		To: "/categories/emulators/memu",
		Categories: "Emulators",
		Windows: "Windows",
		Apps: "",
		desc: "Memu is an Android emulator that specializes in video games, thanks to which you can enjoy any of the many exclusive titles you can find for mobile phones and tablets, directly on your computer.    ",
		olderversions: Nootherversion(),
		filename: "Memu-Setup",
		setupsize: "435MB",
		Free: "Free",
		dev: "Memu",
		devhref: "https://www.memuplay.com/",
		sysos: "Windows 7, 8.1, 10",
		sysram: " 4GB",
		type: "Offline Installer",
		sysarch: '×32, ×64',
		Download: <div><Downloadbtn to='https://dl.memuplay.com/download/Memu-Setup.exe' className="mb-3" color="btn btn-primary" Version="Windows" /></div>
	},
	{
		Name: "Nox Player",
		img: "/media/images/100x100/Emulators/nox.png",
		To: "/categories/emulators/nox-player",
		Categories: "Emulators",
		Windows: "Windows",
		Apps: "",
		desc: "Nox App Player is an emulator that enables you to play games on Windows PC and also for the Mac devices. The player also increases the basic capacities of games and applications and offers enhanced graphics. In short, the emulator implements efficient and effective extension controls on the device you have to use the Nox App Player.",
		olderversions: Nootherversion(),
		filename: "Nox Setup",
		setupsize: "430MB",
		Free: "Free",
		dev: "Nox",
		devhref: "https://noxofficial.com/",
		sysos: "Windows 7, 8.1, 10",
		sysram: " 4GB",
		type: "Offline Installer",
		sysarch: '×32, ×64',
		Download: <div><Downloadbtn to='https://noxofficial.com/windows-zip-package' className="mb-3" color="btn btn-primary" Version="Windows" /></div>
	},
	{
		Name: "Smart Gaga",
		img: "/media/images/100x100/Emulators/smartgaga.jpg",
		To: "/categories/emulators/smart-gaga",
		Categories: "Emulators",
		Windows: "Windows",
		Apps: "",
		desc: "Smart Gaga is the most advisable Android simulator for low and medium range PCs. It is fast and agile thanks to the fact that it is created with the Titan engine, the most advanced technology among non-virtual Android emulators. This facilitates a notable reduction in the load on the machine, as well as the consumption of performance memory.",
		olderversions: Nootherversion(),
		filename: "SmartGaGa_Android_Emulator_v1.1.646.1",
		setupsize: "205MB",
		Free: "Free",
		dev: "Smart-gaga",
		// devhref:"",
		sysos: "Windows 7, 8.1, 10",
		sysram: " 4GB",
		type: "Offline Installer",
		sysarch: '×32, ×64',
		Download: <div><Downloadbtn to='https://www.dropbox.com/s/w9zsowvk5r1qm52/SmartGaGa.exe?dl=1' className="mb-3" color="btn btn-primary" Version="Windows" /></div>
	},
	{
		Name: "YouWave",
		img: "/media/images/100x100/Emulators/youwave.jpg",
		To: "/categories/emulators/youwave",
		Categories: "Emulators",
		Windows: "Windows",
		Apps: "",
		desc: "YouWave is a free and open source Android emulator software download filed under console emulators and made available by YouWave Inc. for Windows.",
		olderversions: Nootherversion(),
		filename: "YouWave-Android-Free-3-31",
		setupsize: "145MB",
		Free: "Free",
		dev: "YouWave",
		devhref: "https://youwave.com/",
		sysos: "Windows 7, 8.1, 10",
		sysram: " 4GB",
		type: "Offline Installer",
		sysarch: '×64',
		Download: <div><V v="v3.31" /><Downloadbtn to='https://youwave.com/dl.php?prod=1/dl.php?prod=1' className="mb-3" color="btn btn-primary" Version="Windows" /></div>
	},
	{
		Name: "Anaconda",
		img: "/media/images/100x100/ide/anaconda.jpg",
		To: "/categories/ide/anconda",
		Categories: "IDE",
		Windows: "Windows",
		Apps: "",
		desc: "Anaconda is a distribution of the Python and R programming languages for scientific computing (data science, machine learning applications, large-scale data processing, predictive analytics, etc.), that aims to simplify package management and deployment. The distribution includes data-science packages suitable for Windows, Linux, and macOS. It is developed and maintained by Anaconda, Inc.",
		olderversions: Nootherversion(),
		filename: "Anaconda3-2021.05-Windows",
		setupsize: "477MB for ×64, 410MB for ×32",
		Free: "Free",
		dev: "Anaconda",
		devhref: "https://www.anaconda.com/",
		sysos: "Windows 7, 8.1, 10",
		sysram: " 4GB",
		type: "Offline Installer",
		sysarch: '×64 ×32',
		Download: <div><Downloadbtn to='https://repo.anaconda.com/archive/Anaconda3-2021.05-Windows-x86_64.exe' className="mb-3" color="btn btn-primary" Version="&times;64 Windows" /><Downloadbtn to='https://repo.anaconda.com/archive/Anaconda3-2021.05-Windows-x86.exe' className="mb-3" color="btn btn-primary" Version="&times;64 Windows" /></div>
	},
	{
		Name: "Android Studio",
		img: "/media/images/100x100/ide/android-studio.jpg",
		To: "/categories/ide/android-studio",
		Categories: "IDE",
		Windows: "Windows",
		Apps: "",
		desc: "Android Studio is the official integrated development environment (IDE) for Google's Android operating system. And is used to develope applications for Android operating system from the programming languages like Kotlin, Java.",
		olderversions: Nootherversion(),
		filename: "android-studio-ide-202.7351085-windows",
		setupsize: "935MB",
		Free: "Free",
		dev: "Andtoid Studio",
		devhref: "https://developer.android.com/studio",
		sysos: "Windows 7, 8.1, 10",
		sysram: " 4GB",
		type: "Offline Installer",
		sysarch: '×64',
		Download: <div><Downloadbtn to='https://redirector.gvt1.com/edgedl/android/studio/install/4.2.1.0/android-studio-ide-202.7351085-windows.exe' className="mb-3" color="btn btn-primary" Version="&times;64 Windows" /></div>
	},
	{
		Name: "Atom",
		img: "/media/images/100x100/ide/atom.jpg",
		To: "/categories/ide/atom",
		Categories: "IDE",
		Windows: "Windows",
		Apps: "",
		desc: "Atom is the IDE developed by Github, has many features for programming more efficients and easily supported many languages with package control.",
		olderversions: Nootherversion(),
		filename: "AtomSetup-x64",
		setupsize: "200MB",
		Free: "Free",
		dev: "Atom",
		devhref: "https://atom.io/",
		sysos: "Windows 7, 8.1, 10",
		sysram: " 4GB",
		type: "Offline Installer",
		sysarch: '×64',
		Download: <div><Downloadbtn to='https://atom.io/download/windows_x64' className="mb-3" color="btn btn-primary" Version="&times;64 Windows" /></div>
	},
	{
		Name: "Brackets",
		img: "/media/images/100x100/ide/brackets.png",
		To: "/categories/ide/brackets",
		Categories: "IDE",
		Windows: "Windows",
		Apps: "",
		desc: "Brackets is the IDE for developing HTML, CSS, JS files developed by Adobe. (Note : Adobe has ended the support for Brackets we recomment download Visual Studio Code IDE.)",
		olderversions: Nootherversion(),
		filename: "Brackets.Release.1.14.2",
		setupsize: "78MB",
		Free: "Free",
		dev: "Brackets",
		devhref: "http://brackets.io/",
		sysos: "Windows 7, 8.1, 10",
		sysram: " 4GB",
		type: "Offline Installer",
		sysarch: '×32 ×64',
		Download: <div><h6>Adobe will end the support for Brackets. We recommend to use <Link to="/categories/ide/vscode">Visual Studio Code</Link></h6><Downloadbtn to='https://get-softwares.github.io/brackets/Brackets.Release.1.14.2.msi' className="mb-3" color="btn btn-primary" Version="Windows" /></div>
	},
	{
		Name: "CLion",
		img: "/media/images/100x100/ide/clion.jpg",
		To: "/categories/ide/c-lion",
		Categories: "IDE",
		Windows: "Windows",
		Apps: "",
		desc: "CLion is the IDE for working in C, C++ languages with many features for code more easily and developed by Jetbrains",
		olderversions: Nootherversion(),
		filename: "CLion-2021.1.2",
		setupsize: "540MB",
		Free: "Trial",
		dev: "Jetbrains",
		devhref: "https://www.jetbrains.com/clion/",
		sysos: "Windows 7, 8.1, 10",
		sysram: " 4GB",
		type: "Offline Installer",
		sysarch: '×64',
		Download: <div><Downloadbtn to='https://download-cdn.jetbrains.com/cpp/CLion-2021.1.2.exe' className="mb-3" color="btn btn-primary" Version="&times;64 Windows" /></div>
	},
	{
		Name: "Eclipse IDE",
		img: "/media/images/100x100/ide/eclipse.jpg",
		To: "/categories/ide/eclipse",
		Categories: "IDE",
		Windows: "Windows",
		Apps: "",
		desc: "Eclipse is an integrated development environment (IDE) used in computer programming. It contains a base workspace and an extensible plug-in system for customizing the environment.",
		olderversions: Nootherversion(),
		filename: "eclipse-win64",
		setupsize: "82MB",
		Free: "Free",
		dev: "Eclipse",
		devhref: "https://www.eclipse.org/",
		sysos: "Windows 7, 8.1, 10",
		sysram: " 4GB",
		type: "Offline Installer",
		sysarch: '×64',
		Download: <div><Downloadbtn to='https://get-softwares.github.io/eclipse/eclipse-win64.zip' className="mb-3" color="btn btn-primary" Version="&times;64 Windows" /></div>
	},
	{
		Name: "Intellij",
		img: "/media/images/100x100/ide/intellij.png",
		To: "/categories/ide/intellij",
		Categories: "IDE",
		Windows: "Windows",
		Apps: "",
		desc: "IntelliJ is one of the most powerful and popular Integrated Development Environments (IDE) for Java. It is developed and maintained by JetBrains and available as community and ultimate edition. This feature rich IDE enables rapid development and helps in improving code quality.",
		olderversions: Nootherversion(),
		filename: "ideaIC-2021.1.2",
		setupsize: "730MB",
		Free: "Free",
		dev: "Jetbrains",
		devhref: "https://www.jetbrains.com/idea/",
		sysos: "Windows 7, 8.1, 10",
		sysram: " 4GB",
		type: "Offline Installer",
		sysarch: '×64',
		Download: <div><Downloadbtn to='https://download-cdn.jetbrains.com/idea/ideaIC-2021.1.2.exe' className="mb-3" color="btn btn-primary" Version="&times;64 Windows" /></div>
	},
	{
		Name: "Notepad++",
		img: "/media/images/100x100/ide/npp.jpg",
		To: "/categories/ide/npp",
		Categories: "IDE",
		Windows: "Windows",
		Apps: "",
		desc: "Notepad++ is a source code editor. It features syntax highlighting, code folding and limited autocompletion for programming, scripting, and markup languages, but not intelligent code completion or syntax checking.",
		olderversions: Nootherversion(),
		filename: "npp.7.9.5.Installer",
		setupsize: "4MB",
		Free: "Free",
		dev: "Notepad++",
		devhref: "https://notepad-plus-plus.org/",
		sysos: "Windows 7, 8.1, 10",
		sysram: " 4GB",
		type: "Offline Installer",
		sysarch: '×32 ×64',
		Download: <div><Downloadbtn to='https://get-softwares.github.io/npp/npp.7.9.5.Installer.exe' className="mb-3" color="btn btn-primary" Version="Windows" /></div>
	},
	{
		Name: "PHP Storm",
		img: "/media/images/100x100/ide/phpstorm.png",
		To: "/categories/ide/php-storm",
		Categories: "IDE",
		Windows: "Windows",
		Apps: "",
		desc: "PhpStorm is an IDE (Integrated Development Environment) for PHP and web developers, which is engineered by JetBrains. It is not available free of cost. It supports PHP 5.3 and above versions. PhpStorm is built on the IntelliJ IDEA platform, which is written in Java",
		olderversions: Nootherversion(),
		filename: "PhpStorm-2021.1.2",
		setupsize: "400MB",
		Free: "Trial",
		dev: "Jetbrains",
		devhref: "https://www.jetbrains.com/phpstorm/",
		sysos: "Windows 7, 8.1, 10",
		sysram: " 4GB",
		type: "Offline Installer",
		sysarch: '×64',
		Download: <div><Downloadbtn to='https://download-cdn.jetbrains.com/webide/PhpStorm-2021.1.2.exe' className="mb-3" color="btn btn-primary" Version="&times;64 Windows" /></div>
	},
	{
		Name: "Pycharm",
		img: "/media/images/100x100/ide/pycharm.jpg",
		To: "/categories/ide/pycharm",
		Categories: "IDE",
		Windows: "Windows",
		Apps: "",
		desc: "PyCharm is an integrated development environment (IDE) used in computer programming, specifically for the Python language. It is developed by the Czech company JetBrains.",
		olderversions: Nootherversion(),
		filename: "pycharm-community-2021.1.1",
		setupsize: "370MB",
		Free: "Free",
		dev: "Jetbrains",
		devhref: "https://www.jetbrains.com/pycharm/",
		sysos: "Windows 7, 8.1, 10",
		sysram: " 4GB",
		type: "Offline Installer",
		sysarch: '×64',
		Download: <div><Downloadbtn to='https://download-cdn.jetbrains.com/python/pycharm-community-2021.1.1.exe' className="mb-3" color="btn btn-primary" Version="&times;64 Windows" /></div>
	},
	{
		Name: "Ruby Mine",
		img: "/media/images/100x100/ide/rubymine.jpg",
		To: "/categories/ide/ruby-mine",
		Categories: "IDE",
		Windows: "Windows",
		Apps: "",
		desc: "JetBrains RubyMine is a commercial IDE for Ruby and Ruby on Rails built on JetBrains' IntelliJ IDEA platform. RubyMine provides intelligent code completion for Ruby and Ruby on Rails code, on-the-fly code analysis and refactoring support for both plain Ruby projects and web applications built with Ruby on Rails.",
		olderversions: Nootherversion(),
		filename: "RubyMine-2021.1.2",
		setupsize: "370MB",
		Free: "Trial",
		dev: "Jetbrains",
		devhref: "https://www.jetbrains.com/ruby/",
		sysos: "Windows 7, 8.1, 10",
		sysram: " 4GB",
		type: "Offline Installer",
		sysarch: '×64',
		Download: <div><Downloadbtn to='https://download-cdn.jetbrains.com/ruby/RubyMine-2021.1.2.exe' className="mb-3" color="btn btn-primary" Version="&times;64 Windows" /></div>
	},
	{
		Name: "R Studio",
		img: "/media/images/100x100/ide/r-studio.jpg",
		To: "/categories/ide/r-studio",
		Categories: "IDE",
		Windows: "Windows",
		Apps: "",
		desc: "RStudio is an integrated development environment (IDE) for R, a programming language for statistical computing and graphics.",
		olderversions: Nootherversion(),
		filename: "RStudio-1.4.1717",
		setupsize: "150MB",
		Free: "Free",
		dev: "R-Studio",
		devhref: "https://www.rstudio.com/",
		sysos: "Windows 7, 8.1, 10",
		sysram: " 4GB",
		type: "Offline Installer",
		sysarch: '×32 ×64',
		Download: <div><Downloadbtn to='https://download1.rstudio.org/desktop/windows/RStudio-1.4.1717.exe' className="mb-3" color="btn btn-primary" Version="Windows" /></div>
	},
	{
		Name: "Sublime",
		img: "/media/images/100x100/ide/sublime.jpg",
		To: "/categories/ide/sublime",
		Categories: "IDE",
		Windows: "Windows",
		Apps: "",
		desc: "Sublime Text is a shareware cross-platform source code editor with a Python application programming interface (API). It natively supports many programming languages and markup languages, and functions can be added by users with plugins, typically community-built and maintained under free-software licenses .",
		olderversions: Nootherversion(),
		filename: "sublime_text_build_4107_x64_setup.exe",
		setupsize: "19MB",
		Free: "Trial",
		dev: "Sublime",
		devhref: "https://www.sublimetext.com/",
		sysos: "Windows 7, 8.1, 10",
		sysram: " 4GB",
		type: "Offline Installer",
		sysarch: '×32 ×64',
		Download: <div><Downloadbtn to='https://get-softwares.github.io/sublime/sublime_text_build_4107_x64_setup.exe' className="mb-3" color="btn btn-primary" Version="Windows" /></div>
	},
	{
		Name: "VS Code",
		img: "/media/images/100x100/ide/vscode.jpg",
		To: "/categories/ide/vscode",
		Categories: "IDE",
		Windows: "Windows",
		Apps: "",
		desc: "Visual Studio Code is a freeware source-code editor made by Microsoft for Windows, Linux and macOS. Features include support for debugging, syntax highlighting, intelligent code completion, snippets, code refactoring, and embedded Git. Users can change the theme, keyboard shortcuts, preferences, and install extensions that add additional functionality.",
		olderversions: Nootherversion(),
		filename: "VSCodeUseSetup",
		setupsize: "378MB",
		Free: "Free",
		dev: "VS Code",
		devhref: "https://code.visualstudio.com/",
		sysos: "Windows 7, 8.1, 10",
		sysram: " 2GB",
		type: "Offline Installer",
		sysarch: '×64',
		Download: <div><V v="v1.56" /><Downloadbtn to='https://code.visualstudio.com/sha/download?build=stable&amp;os=win32-user' className="mb-3" color="btn btn-primary" Version="&times;32 Windows" /><Downloadbtn to='https://code.visualstudio.com/sha/download?build=stable&amp;os=win32-x64-user' className="mb-3" color="btn btn-primary" Version="&times;64 Windows" /></div>
	},
	{
		Name: "Web Storm",
		img: "/media/images/100x100/ide/webstorm.png",
		To: "/categories/ide/web-storm",
		Categories: "IDE",
		Windows: "Windows",
		Apps: "",
		desc: "JetBrains WebStorm is a commercial IDE for JavaScript, CSS & HTML built on JetBrains' IntelliJ IDEA platform. WebStorm is a specialized version of PhpStorm, offering a subset of its features. WebStorm ships with pre-installed JavaScript plugins, which are available for PhpStorm. WebStorm provides automatic code completion, on-the-fly code analysis, refactoring support and VCS integration. Supported languages are JavaScript, CoffeeScript, TypeScript and Dart.",
		olderversions: Nootherversion(),
		filename: "WebStorm-2021.1.2",
		setupsize: "378MB",
		Free: "Trial",
		dev: "Jetbrains",
		devhref: "https://www.jetbrains.com/webstorm/",
		sysos: "Windows 7, 8.1, 10",
		sysram: " 4GB",
		type: "Offline Installer",
		sysarch: '×64',
		Download: <div><Downloadbtn to='https://download-cdn.jetbrains.com/webstorm/WebStorm-2021.1.2.exe' className="mb-3" color="btn btn-primary" Version="&times;64 Windows" /></div>
	},
	{
		Name: "5K Player",
		img: "/media/images/100x100/m-player/5k-player.jpg",
		To: "/categories/media-player/5k-player",
		Categories: "Media Player",
		Windows: "Windows",
		Apps: "",
		desc: "5KPlayer is a free-to-use, feature-loaded, and easy-to-use multimedia player. Unlike most programs in this category, this one comes with mirroring and downloading functionalities. Developed for Windows, 5KPlayer has a built-in hardware accelerator, which ensures quick rendering of 8K video formats without crashes or lags.",
		olderversions: Nootherversion(),
		filename: "5kplayer",
		setupsize: "50MB",
		Free: "Free",
		dev: "5k player",
		devhref: "https://www.5kplayer.com/",
		sysos: "Windows 7, 8.1, 10",
		sysram: " 2GB",
		type: "Offline Installer",
		sysarch: '×64, ×32',
		Download: <div><Downloadbtn to='https://get-softwares.github.io/5k-player/5kplayer-64bit.exe' className="mb-3" color="btn btn-primary" Version="&times;64 Windows" /><Downloadbtn to='https://get-softwares.github.io/5k-player/5kplayer-32bit.exe' className="mb-3" color="btn btn-primary" Version="&times;32 Windows" /></div>
	},
	{
		Name: "All Player",
		img: "/media/images/100x100/m-player/all-player.jpg",
		To: "/categories/media-player/all-player",
		Categories: "Media Player",
		Windows: "Windows",
		Apps: "",
		desc: "ALLPlayer is a cross-platform media player and streaming media server written by ALLPlaye Group Ltd. ALLPlayer is available for desktop Windows and mobile platforms, such as Android, iPad and iPhone iOS.",
		olderversions: Nootherversion(),
		filename: "ALLPlayerWindows",
		setupsize: "110MB",
		Free: "Free",
		dev: "All player",
		devhref: "https://www.allplayer.org/",
		sysos: "Windows 7, 8.1, 10",
		sysram: " 2GB",
		type: "Offline Installer",
		sysarch: '×64, ×32',
		Download: <div><Downloadbtn to='https://www.dropbox.com/s/5z0oh5qo0vd1luv/ALLPlayerWindows.exe?dl=1' className="mb-3" color="btn btn-primary" Version="Windows" /></div>
	},
	{
		Name: "DivX",
		img: "/media/images/100x100/m-player/divx.jpg",
		To: "/categories/media-player/divx-player",
		Categories: "Media Player",
		Windows: "Windows",
		Apps: "",
		desc: "DivX is a brand of video codec products developed by DivX, LLC. There are three DivX codecs: the original MPEG-4 Part 2 DivX codec, the H.264/MPEG-4 AVC DivX Plus HD codec and the High Efficiency Video Coding DivX HEVC Ultra HD codec.",
		olderversions: Nootherversion(),
		filename: "WebStorm-2021.1.2",
		setupsize: "110MB",
		Free: "Trial",
		dev: "Divx",
		devhref: "https://www.divx.com/",
		sysos: "Windows 7, 8.1, 10",
		sysram: " 2GB",
		type: "Online Installer",
		sysarch: '×64, ×32',
		Download: <div><Downloadbtn to='https://get-softwares.github.io/divx/DivXInstaller.exe' className="mb-3" color="btn btn-primary" Version="Windows" /></div>
	},
	{
		Name: "GOM Player",
		img: "/media/images/100x100/m-player/gom-player.jpg",
		To: "/categories/media-player/gom-player",
		Categories: "Media Player",
		Windows: "Windows",
		Apps: "Apps",
		desc: "GOM Player is a media player for Windows, developed by GOM & Company. With more than 100 million downloads, it is also known as the most used player in South Korea. Its main features include the ability to play some broken media files and find missing codecs using a codec finder service.",
		olderversions: Nootherversion(),
		filename: "GOMPLAYERGLOBALSETUP_CHROME for Windows, GOM-Player for Android",
		setupsize: "55MB for Andorid, 25MB for Windows",
		Free: "Free",
		dev: "Divx",
		devhref: "https://www.divx.com/",
		sysos: "Windows 7, 8.1, 10",
		sysram: " 2GB",
		type: "Offline Installer",
		sysarch: '×64, ×32',
		Download: <div><Downloadbtn to='https://get-softwares.github.io/gom-player/GOMPLAYERGLOBALSETUP.EXE' className="mb-3" color="btn btn-primary" Version="Windows" /><Downloadbtn to='https://get-softwares.github.io/gom-player/GOM-Player.apk' className="mb-3" color="btn btn-primary" Version="Android" /></div>
	},
	{
		Name: "KM Player",
		img: "/media/images/100x100/m-player/km-player.jpg",
		To: "/categories/media-player/km-player",
		Categories: "Media Player",
		Windows: "Windows",
		Apps: "Apps",
		desc: "KMPlayer is considered a universal video player as it offers users a range of features and functions designed to help you watch videos, scroll through images, and play audio files. It is a program that most users rely on to play MKV files, Blu-ray content, 3D videos, and more.",
		olderversions: Nootherversion(),
		filename: "KMP64_2021.04.27.54 for x64 Windows, KMPlayer_4.2.2.51 for x32 Windows, KMPlayer for Android",
		setupsize: "112MB for Andorid, 50MB for Windows",
		Free: "Free",
		dev: "KM player",
		devhref: "https://www.kmplayer.com/home",
		sysos: "Windows 7, 8.1, 10",
		sysram: " 2GB",
		type: "Offline Installer",
		sysarch: '×64, ×32',
		Download: <div><Downloadbtn to='https://get-softwares.github.io/km-player/KMP64_2021.04.27.54.exe' className="mb-3" color="btn btn-primary" Version="&times;64 Windows" /><Downloadbtn to='https://get-softwares.github.io/km-player/KMPlayer_4.2.2.51.exe' className="mb-3" color="btn btn-primary" Version="&times;32 Windows" /><Downloadbtn to='https://get-softwares.github.io/km-player/KMPlayer.zip' className="mb-3" color="btn btn-primary" Version="Android" /></div>
	},
	{
		Name: "Pot Player",
		img: "/media/images/100x100/m-player/pot-player.jpg",
		To: "/categories/media-player/pot-player",
		Categories: "Media Player",
		Windows: "Windows",
		Apps: "",
		desc: "PotPlayer is a multimedia software player developed for the Microsoft Windows operating system by South Korean Internet company Kakao (formerly Daum Communications). It competes with other popular Windows media players such as VLC media player, GOM Player, KMPlayer, SMPlayer and Media Player Classic.",
		olderversions: Nootherversion(),
		filename: "PotPlayerSetup32 for x32 Windows, PotPlayerSetup64 Windows",
		setupsize: "30MB",
		Free: "Free",
		dev: "Pot player",
		devhref: "https://potplayer.daum.net/",
		sysos: "Windows 7, 8.1, 10",
		sysram: " 2GB",
		type: "Offline Installer",
		sysarch: '×64, ×32',
		Download: <div><Downloadbtn to='https://get-softwares.github.io/pot-player/PotPlayerSetup64.exe' className="mb-3" color="btn btn-primary" Version="&times;64 Windows" /><Downloadbtn to='https://get-softwares.github.io/pot-player/PotPlayerSetup.exe' className="mb-3" color="btn btn-primary" Version="&times;32 Windows" /></div>
	},
	{
		Name: "SM Player",
		img: "/media/images/100x100/m-player/sm-player.jpg",
		To: "/categories/media-player/sm-player",
		Categories: "Media Player",
		Windows: "Windows",
		Apps: "",
		desc: "SMPlayer is a free media player for Windows and Linux with built-in codecs that can play virtually all video and audio formats. It doesn't need any external codecs. Just install SMPlayer and you'll be able to play all formats without the hassle to find and install codec packs.",
		olderversions: Nootherversion(),
		filename: "smplayer-21.1.0-win32 for x32 Windows, smplayer-21.1.0-x64 Windows",
		setupsize: "30MB",
		Free: "Free",
		dev: "SM player",
		devhref: "https://www.smplayer.info/",
		sysos: "Windows 7, 8.1, 10",
		sysram: " 2GB",
		type: "Offline Installer",
		sysarch: '×64, ×32',
		Download: <div><Downloadbtn to='https://get-softwares.github.io/sm-player/smplayer-21.1.0-x64.exe' className="mb-3" color="btn btn-primary" Version="&times;64 Windows" /><Downloadbtn to='https://get-softwares.github.io/sm-player/smplayer-21.1.0-win32.exe' className="mb-3" color="btn btn-primary" Version="&times;32 Windows" /></div>
	},
	{
		Name: "VLC Media Player",
		img: "/media/images/100x100/m-player/vlc-media-player.jpg",
		To: "/categories/media-player/vlc-media-player",
		Categories: "Media Player",
		Windows: "Windows",
		Apps: "Apps",
		desc: "VLC media player VLC is a free and open source cross-platform multimedia player and framework that plays most multimedia files as well as DVDs, Audio CDs, VCDs, and various streaming protocols.",
		olderversions: Nootherversion(),
		filename: "vlc-3.0.12-win64 for Windows, VLC Android",
		setupsize: "30MB",
		Free: "Free",
		dev: "Videolan",
		devhref: "https://www.videolan.org/vlc/",
		sysos: "Windows 7, 8.1, 10",
		sysram: " 4GB",
		type: "Offline Installer",
		sysarch: '×64',
		Download: <div><Downloadbtn to='https://get-softwares.github.io/vlc-media-player/vlc-3.0.12-win64.exe' className="mb-3" color="btn btn-primary" Version="&times;64 Windows" /><Downloadbtn to='https://get-softwares.github.io/vlc-media-player/VLC.apk' className="mb-3" color="btn btn-primary" Version="Android" /></div>
	},
	{
		Name: "Free Office",
		img: "/media/images/100x100/office/free-office.jpg",
		To: "/categories/office-softwares/free-office",
		Categories: "Office Softwares",
		Windows: "Windows",
		Apps: "",
		desc: "Free Office is the office available in free of cost and includes presentation, textmaker, excel.",
		olderversions: Nootherversion(),
		filename: "FreeOffice2019",
		setupsize: "112MB",
		Free: "Free",
		dev: "Free Office",
		devhref: "https://www.freeoffice.com/en/",
		sysos: "Windows 7, 8.1, 10",
		sysram: " 3GB",
		type: "Offline Installer",
		sysarch: '×32 ×64',
		Download: <div><Downloadbtn to='https://www.freeoffice.com/download.php?filename=https://www.softmaker.net/down/freeoffice2018.msi' className="mb-3" color="btn btn-primary" Version="Windows" /></div>
	},
	{
		Name: "Google Docs",
		img: "/media/images/100x100/office/app/google docs.png",
		To: "/categories/office-softwares/google-docs",
		Categories: "Office Softwares",
		Apps: "Apps",
		Windows: "",
		desc: "Google Docs is the application for android to make text document through your phone and developed by Google",
		olderversions: Nootherversion(),
		filename: "Google Docs",
		setupsize: "62MB",
		Free: "Free",
		dev: "Google",
		devhref: "https://docs.google.com/",
		sysos: "Android",
		sysram: " 1GB",
		type: "Offline Installer",
		sysarch: '×32 ×64',
		Download: <div><Downloadbtn to='https://get-softwares.github.io/google-docs/Google Docs.apk' className="mb-3" color="btn btn-primary" Version="Android" /></div>
	},
	{
		Name: "Google Sheets",
		img: "/media/images/100x100/office/app/google sheets.png",
		To: "/categories/office-softwares/google-sheets",
		Categories: "Office Softwares",
		Apps: "Apps",
		Windows: "",
		desc: "Google Sheets is the application for android to make sheets and manage the datas through your phone and developed by Google.",
		olderversions: Nootherversion(),
		filename: "Google Sheets",
		setupsize: "40MB",
		Free: "Free",
		dev: "Google",
		devhref: "https://www.google.com/sheets/about/",
		sysos: "Android",
		sysram: " 1GB",
		type: "Offline Installer",
		sysarch: '×32 ×64',
		Download: <div><Downloadbtn to='https://get-softwares.github.io/google-sheets/Google Sheets.xapk' className="mb-3" color="btn btn-primary" Version="Android" /></div>
	},
	{
		Name: "Google Slides",
		img: "/media/images/100x100/office/app/google slides.png",
		To: "/categories/office-softwares/google-slides",
		Categories: "Office Softwares",
		Apps: "Apps",
		Windows: "",
		desc: "Google Slides is the application for android to make presentation through your phone and developed by Google.",
		olderversions: Nootherversion(),
		filename: "Google Slides",
		setupsize: "47MB",
		Free: "Free",
		dev: "Google",
		devhref: "https://www.google.com/slides/about/",
		sysos: "Android",
		sysram: " 1GB",
		type: "Offline Installer",
		sysarch: '×32 ×64',
		Download: <div><Downloadbtn to='https://get-softwares.github.io/google-slides/Google Slides.xapk' className="mb-3" color="btn btn-primary" Version="Android" /></div>
	},
	{
		Name: "Microsoft Excel",
		img: "/media/images/100x100/office/app/microsoft excel.jpg",
		To: "/categories/office-softwares/ms-excel",
		Categories: "Office Softwares",
		Apps: "Apps",
		Windows: "",
		desc: "Microsoft Excel is the android application to manage datas in spreadsheet format with so many features in free of cost. (for application only)",
		olderversions: Nootherversion(),
		filename: "Microsoft Excel",
		setupsize: "65.2MB",
		Free: "Free",
		dev: "Microsoft",
		devhref: "https://www.microsoft.com/en-in/",
		sysos: "Android",
		sysram: " 1GB",
		type: "Offline Installer",
		sysarch: '×32 ×64',
		Download: <div><Downloadbtn to='https://get-softwares.github.io/ms-excel-app/Microsoft Excel.apk' className="mb-3" color="btn btn-primary" Version="Android" /></div>
	},
	{
		Name: "Microsoft Office",
		img: "/media/images/100x100/office/app/microsoft office.jpg",
		To: "/categories/office-softwares/ms-office",
		Categories: "Office Softwares",
		Apps: "Apps",
		Windows: "",
		desc: "Microsoft Office is the free office for android.",
		olderversions: Nootherversion(),
		filename: "Microsoft Office",
		setupsize: "100MB",
		Free: "Free",
		dev: "Microsoft",
		devhref: "https://www.microsoft.com/en-in/",
		sysos: "Android",
		sysram: " 1GB",
		type: "Offline Installer",
		sysarch: '×32 ×64',
		Download: <div><Downloadbtn to='https://get-softwares.github.io/ms-office/Microsoft Office.xapk' className="mb-3" color="btn btn-primary" Version="Android" /></div>
	},
	{
		Name: "Microsoft Onenote",
		img: "/media/images/100x100/office/app/microsoft onenote.png",
		To: "/categories/office-softwares/ms-onenote",
		Categories: "Office Softwares",
		Apps: "Apps",
		Windows: "",
		desc: "Microsoft Onenote is the android application to make notes. (for application only)",
		olderversions: Nootherversion(),
		filename: "Microsoft OneNote",
		setupsize: "70MB",
		Free: "Free",
		dev: "Microsoft",
		devhref: "https://www.microsoft.com/en-in/",
		sysos: "Android",
		sysram: " 1GB",
		type: "Offline Installer",
		sysarch: '×32 ×64',
		Download: <div><Downloadbtn to='https://get-softwares.github.io/ms-onenote/Microsoft OneNote.apk' className="mb-3" color="btn btn-primary" Version="Android" /></div>
	},
	{
		Name: "Microsoft Outlook",
		img: "/media/images/100x100/office/app/microsoft outlook.png",
		To: "/categories/office-softwares/ms-outlook",
		Categories: "Office Softwares",
		Apps: "Apps",
		Windows: "",
		desc: "Microsoft Outlook is the android application to manage outlook mail send mails in free of cost. (for application only)",
		olderversions: Nootherversion(),
		filename: "Microsoft Outlook",
		setupsize: "708MB",
		Free: "Free",
		dev: "Microsoft",
		devhref: "https://www.microsoft.com/en-in/",
		sysos: "Android",
		sysram: " 1GB",
		type: "Offline Installer",
		sysarch: '×32 ×64',
		Download: <div><Downloadbtn to='https://get-softwares.github.io/ms-outlook/Microsoft Outlook.apk' className="mb-3" color="btn btn-primary" Version="Android" /></div>
	},
	{
		Name: "Microsoft Planner",
		img: "/media/images/100x100/office/app/microsoft planner.jpg",
		To: "/categories/office-softwares/ms-planner",
		Categories: "Office Softwares",
		Apps: "Apps",
		Windows: "",
		desc: "Microsoft Planner is the android application to make a plans in text format with so many features in free of cost. (for application only)",
		olderversions: Nootherversion(),
		filename: "Microsoft Planner",
		setupsize: "15MB",
		Free: "Free",
		dev: "Microsoft",
		devhref: "https://www.microsoft.com/en-in/",
		sysos: "Android",
		sysram: " 1GB",
		type: "Offline Installer",
		sysarch: '×32 ×64',
		Download: <div><Downloadbtn to='https://get-softwares.github.io/ms-planner/Microsoft Planner.apk' className="mb-3" color="btn btn-primary" Version="Android" /></div>
	},
	{
		Name: "Microsoft Powerpoint",
		img: "/media/images/100x100/office/app/microsoft powerpoint.png",
		To: "/categories/office-softwares/ms-powerpoint",
		Categories: "Office Softwares",
		Apps: "Apps",
		Windows: "",
		desc: "Microsoft Powerpoint is the android application to make a Powerpoint Presentation with so many features in free of cost. (for application only)",
		olderversions: Nootherversion(),
		filename: "Microsoft PowerPoint",
		setupsize: "63MB",
		Free: "Free",
		dev: "Microsoft",
		devhref: "https://www.microsoft.com/en-in/",
		sysos: "Android",
		sysram: " 1GB",
		type: "Offline Installer",
		sysarch: '×32 ×64',
		Download: <div><Downloadbtn to='https://get-softwares.github.io/ms-powerpoint/Microsoft PowerPoint.apk' className="mb-3" color="btn btn-primary" Version="Android" /></div>
	},
	{
		Name: "Microsoft Word",
		img: "/media/images/100x100/office/app/Microsoft-Word.png",
		To: "/categories/office-softwares/ms-word",
		Categories: "Office Softwares",
		Apps: "Apps",
		Windows: "",
		desc: "Microsoft Word is the android application to make a text document with so many features in free of cost. (for application only)",
		olderversions: Nootherversion(),
		filename: "Microsoft Word",
		setupsize: "70MB",
		Free: "Free",
		dev: "Microsoft",
		devhref: "https://www.microsoft.com/en-in/",
		sysos: "Android",
		sysram: " 1GB",
		type: "Offline Installer",
		sysarch: '×32 ×64',
		Download: <div><Downloadbtn to='https://get-softwares.github.io/ms-word/Microsoft Word.apk' className="mb-3" color="btn btn-primary" Version="Android" /></div>
	},
	{
		Name: "Office Suite",
		img: "/media/images/100x100/office/app/office suite.jpg",
		To: "/categories/office-softwares/office-suite-app",
		Categories: "Office Softwares",
		Apps: "Apps",
		Windows: "",
		desc: "Office Suite is the office available for Android that includes presentation, word, excel.",
		olderversions: Nootherversion(),
		filename: "OfficeSuite",
		setupsize: "57MB",
		Free: "Free",
		dev: "Office Suite",
		devhref: "https://www.officesuite.com/hi/",
		sysos: "Android",
		sysram: " 1GB",
		type: "Offline Installer",
		sysarch: '×32 ×64',
		Download: <div><Downloadbtn to='https://get-softwares.github.io/office-suite-app/OfficeSuite.xapk' className="mb-3" color="btn btn-primary" Version="Android" /></div>
	},
	{
		Name: "WPS Office",
		img: "/media/images/100x100/office/app/wps office.jpg",
		To: "/categories/office-softwares/wps-app",
		Categories: "Office Softwares",
		Apps: "Apps",
		Windows: "",
		desc: "WPS Office is the office available for Android in free of cost and includes presentation, textmaker, excel.",
		olderversions: Nootherversion(),
		filename: "WPS Office",
		setupsize: "115MB",
		Free: "Free",
		dev: "WPS",
		devhref: "https://www.wps.com/",
		sysos: "Android",
		sysram: " 1GB",
		type: "Offline Installer",
		sysarch: '×32 ×64',
		Download: <div><Downloadbtn to='https://get-softwares.github.io/wps-office-app/WPS Office.zip' className="mb-3" color="btn btn-primary" Version="Android" /></div>
	},
	{
		Name: "Libre Office",
		img: "/media/images/100x100/office/libre-office.jpg",
		To: "/categories/office-softwares/libre-office",
		Categories: "Office Softwares",
		Windows: "Windows",
		Apps: "",
		desc: "Libre Office is the office available in free of cost and includes all office softwares like excel, word, powepoint, etc.",
		olderversions: Nootherversion(),
		filename: "LibreOffice_7.1.3",
		setupsize: "313MB for x64, 300MB for x32",
		Free: "Free",
		dev: "WPS",
		devhref: "https://www.wps.com/",
		sysos: "Windows",
		sysram: " 1GB",
		type: "Offline Installer",
		sysarch: '×32 ×64',
		Download: <div><V v='7.1.3' /><Downloadbtn to='https://www.libreoffice.org/donate/dl/win-x86_64/7.1.3/en-US/LibreOffice_7.1.3_Win_x64.msi' className="mb-3" color="btn btn-primary" Version="&times;64 Windows" /><Downloadbtn to='https://www.libreoffice.org/donate/dl/win-x86/7.1.3/en-US/LibreOffice_7.1.3_Win_x86.msi' className="mb-3" color="btn btn-primary" Version="&times;32 Windows" /></div>
	},
	{
		Name: "Office Suite",
		img: "/media/images/100x100/office/office-suite.jpg",
		To: "/categories/office-softwares/office-suite",
		Categories: "Office Softwares",
		Windows: "Windows",
		Apps: "",
		desc: "Office suite is a collection of productivity software usually containing a word processor, spreadsheet and a presentation program. There are many different brands and types of office suites.",
		olderversions: Nootherversion(),
		filename: "OfficeSuiteSetup_x64 for x64 Windows, OfficeSuiteSetup_x32 for x32 Windows",
		setupsize: "3MB",
		Free: "Free",
		dev: "Office Suite",
		devhref: "https://www.officesuite.com/",
		sysos: "Windows",
		sysram: " 2GB",
		type: "Online Installer",
		sysarch: '×32 ×64',
		Download: <div><Downloadbtn to='https://get-softwares.github.io/office-suite-windows/OfficeSuiteSetup_x64.exe' className="mb-3" color="btn btn-primary" Version="&times;64 Windows" /><Downloadbtn to='https://get-softwares.github.io/office-suite-windows/OfficeSuiteSetup_x32.exe' className="mb-3" color="btn btn-primary" Version="&times;32 Windows" /></div>
	},
	{
		Name: "WPS Office",
		img: "/media/images/100x100/office/wps-office.jpg",
		To: "/categories/office-softwares/wps-office",
		Categories: "Office Softwares",
		Windows: "Windows",
		Apps: "",
		desc: "WPS Office is an office suite for Microsoft Windows, macOS, Linux, iOS and Android, developed by Zhuhai-based Chinese software developer Kingsoft. WPS Office is made up of three primary components: WPS Writer, WPS Presentation, and WPS Spreadsheet.",
		olderversions: Nootherversion(),
		filename: "WPS Office",
		setupsize: "5MB",
		Free: "Free",
		dev: "WPS",
		devhref: "https://www.wps.com/",
		sysos: "Windows",
		sysram: " 2GB",
		type: "Online Installer",
		sysarch: '×32 ×64',
		Download: <div><Downloadbtn to='https://get-softwares.github.io/wps-office/wps_office_inst.exe' className="mb-3" color="btn btn-primary" Version="Windows" /></div>
	},
	{
		Name: "Adobe Photoshop",
		img: "/media/images/100x100/photo-editor/adobe-photoshop.jpg",
		To: "/categories/photo-editor/adobe-photoshop",
		Categories: "Photo Editor",
		Windows: "Windows",
		Apps: "",
		desc: "Adobe Photoshop is a raster graphics editor developed and published by Adobe Inc. for Windows and macOS. It was originally created in 1988 by Thomas and John Knoll. Since then, the software has become the industry standard not only in raster graphics editing, but in digital art as a whole.",
		olderversions: Nootherversion(),
		filename: "Adobe Photoshop",
		setupsize: "2GB",
		Free: "Paid",
		dev: "Adobe",
		devhref: "https://www.adobe.com/products/photoshop.html",
		sysos: "Windows",
		sysram: " 8GB",
		type: "Online Installer",
		sysarch: '×64',
		Download: <div><Downloadbtn to='https://www.adobe.com/products/photoshop.html?mv=affiliate&amp;mv2=red' className="mb-3" color="btn btn-primary" Version="Windows" /></div>
	},
	{
		Name: "Canva",
		img: "/media/images/100x100/photo-editor/canva.jpg",
		To: "/categories/photo-editor/canva",
		Categories: "Photo Editor",
		Windows: "Windows",
		Apps: "",
		desc: "Canva is a graphic design platform, used to create social media graphics, presentations, posters, documents and other visual content. The app includes templates for users to use. The platform is free to use and offers paid subscriptions like Canva Pro.",
		olderversions: Nootherversion(),
		filename: "Canva Setup",
		setupsize: "110MB",
		Free: "Free",
		dev: "Canva",
		devhref: "https://www.canva.com/download/",
		sysos: "Windows",
		sysram: " 2GB",
		type: "Offline Installer",
		sysarch: '×32 ×64',
		Download: <div><Downloadbtn to='https://desktop-release.canva-deploy.com/Canva%20Setup%201.25.0.exe' className="mb-3" color="btn btn-primary" Version="Windows" /></div>
	},
	{
		Name: "Coreldraw",
		img: "/media/images/100x100/photo-editor/coreldraw.jpg",
		To: "/categories/photo-editor/coreldraw",
		Categories: "Photo Editor",
		Windows: "Windows",
		Apps: "",
		desc: "CorelDRAW is a vector graphics editor developed and marketed by Corel Corporation. It is also the name of the Corel graphics suite, which includes the bitmap-image editor Corel Photo-Paint as well as other graphics-related programs.",
		olderversions: Nootherversion(),
		filename: "CDGS2021",
		setupsize: "2MB",
		Free: "Paid",
		dev: "Coreldraw",
		devhref: "https://www.coreldraw.com/en/",
		sysos: "Windows",
		sysram: " 4GB",
		type: "Online Installer",
		sysarch: '×32 ×64',
		Download: <div><Downloadbtn to='https://get-softwares.github.io/coreldraw/CDGS2021.exe' className="mb-3" color="btn btn-primary" Version="Windows" /></div>
	},
	{
		Name: "GIMP",
		img: "/media/images/100x100/photo-editor/gimp.jpg",
		To: "/categories/photo-editor/gimp",
		Categories: "Photo Editor",
		Windows: "Windows",
		Apps: "",
		desc: "GNU Image Manipulation Program (GIMP). GIMP is a cross-platform image editor available for GNU/Linux, OS X, Windows and more operating systems. It is free software, you can change its source code and distribute your changes.",
		olderversions: Nootherversion(),
		filename: "gimp-2.10.24-setup-3",
		setupsize: "245MB",
		Free: "Free",
		dev: "GIMP",
		devhref: "https://www.gimp.org/",
		sysos: "Windows",
		sysram: " 4GB",
		type: "Offline Installer",
		sysarch: '×32 ×64',
		Download: <div><Downloadbtn to='https://artfiles.org/gimp.org/pub/gimp/v2.10/windows/gimp-2.10.24-setup-3.exe' className="mb-3" color="btn btn-primary" Version="Windows" /></div>
	},
	{
		Name: "Inkscape",
		img: "/media/images/100x100/photo-editor/inkscape.jpg",
		To: "/categories/photo-editor/inkscape",
		Categories: "Photo Editor",
		Windows: "Windows",
		Apps: "",
		desc: "Inkscape is a free and open-source vector graphics editor used to create vector images, primarily in Scalable Vector Graphics format. Other formats can be imported and exported.",
		olderversions: Nootherversion(),
		filename: "inkscape-1.1",
		setupsize: "100MB",
		Free: "Free",
		dev: "Inkscape",
		devhref: "https://inkscape.org/",
		sysos: "Windows",
		sysram: " 4GB",
		type: "Offline Installer",
		sysarch: '×32 ×64',
		Download: <div><Downloadbtn to='https://media.inkscape.org/dl/resources/file/inkscape-1.1-x64.exe' className="mb-3" color="btn btn-primary" Version="Windows &times;64" /><Downloadbtn to='https://media.inkscape.org/dl/resources/file/inkscape-1.1-x86.exe' className="mb-3" color="btn btn-primary" Version="Windows &times;32" /></div>
	},
	{
		Name: "Krita",
		img: "/media/images/100x100/photo-editor/krita.jpg",
		To: "/categories/photo-editor/krita",
		Categories: "Photo Editor",
		Windows: "Windows",
		Apps: "",
		desc: "Krita is a free and open-source raster graphics editor designed primarily for digital painting and 2D animation. It runs on Windows, macOS, Linux, Android and Chrome OS.",
		olderversions: Nootherversion(),
		filename: "krita-x64-4.4.5",
		setupsize: "135MB",
		Free: "Free",
		dev: "Krita",
		devhref: "https://krita.org/en/",
		sysos: "Windows",
		sysram: " 4GB",
		type: "Offline Installer",
		sysarch: '×64',
		Download: <div><Downloadbtn to='https://kde.cs.nctu.edu.tw/ftp/stable/krita/4.4.5/krita-x64-4.4.5-setup.exe' className="mb-3" color="btn btn-primary" Version="Windows &times;64" /></div>
	},
	{
		Name: "Luminar AI",
		img: "/media/images/100x100/photo-editor/luminar-ai.jpg",
		To: "/categories/photo-editor/luminar-ai",
		Categories: "Photo Editor",
		Windows: "Windows",
		Apps: "",
		desc: "Luminar AI is the first photo editing software based on artificial intelligence. It is thanks to AI tools, which do all the work for you, a great choice for beginners.",
		olderversions: Nootherversion(),
		filename: "LuminarAISetup",
		setupsize: "15MB",
		Free: "Trial",
		dev: "Skylum",
		devhref: "https://skylum.com/luminar-ai-b",
		sysos: "Windows",
		sysram: " 4GB",
		type: "Online Installer",
		sysarch: '×64',
		Download: <div><Downloadbtn to='https://kde.cs.nctu.edu.tw/ftp/stable/krita/4.4.5/krita-x64-4.4.5-setup.exe' className="mb-3" color="btn btn-primary" Version="Windows &times;64" /></div>
	},
	{
		Name: "Paint.Net",
		img: "/media/images/100x100/photo-editor/paintnet.jpg",
		To: "/categories/photo-editor/paint-net",
		Categories: "Photo Editor",
		Windows: "Windows",
		Apps: "",
		desc: "Paint.NET delivers a cost-effective alternative to pricey commercial software. Paint.NET is image and photo editing software for PCs that runs on Windows.",
		olderversions: Nootherversion(),
		filename: "paint.net.4.2.16.install.zip",
		setupsize: "15MB",
		Free: "Free",
		dev: "Paint.Net",
		devhref: "https://www.getpaint.net/",
		sysos: "Windows",
		sysram: " 2GB",
		type: "Offline Installer",
		sysarch: '×64',
		Download: <div><Downloadbtn to='https://www.dotpdn.com/files/paint.net.4.2.16.install.zip' className="mb-3" color="btn btn-primary" Version="Windows &times;32 &times;64" /></div>
	},
	{
		Name: "Adobe Reader",
		img: "/media/images/100x100/pdf reader/adobe-reader.jpg",
		To: "/categories/pdf-reader/adobe-reader",
		Categories: "PDF Reader",
		Windows: "Windows",
		Apps: "",
		desc:"Acrobat Reader is the freeware version of Acrobat developed by Adobe Inc. to view, create, fill, print and format files in the Portable Document Format (PDF). It is currently available for Windows, macOS, iOS, and Android users only.",
		olderversions: Nootherversion(),
		filename:"readerdc_en_ka_cra_goca_install",
		setupsize:"1.5MB",
		Free:"Free",
		dev:"Adobe",
		devhref:"https://get.adobe.com/reader/",
		sysos:"Windows",
		sysram:" 2GB",
		type:"Online Installer",
		sysarch:'×64',
		Download:<div><Downloadbtn to='https://admdownload.adobe.com/bin/live/readerdc_en_ka_cra_goca_install.exe' className="mb-3" color="btn btn-primary" Version="Windows"/></div>
	},
	{
		Name: "Foxit Reader",
		img: "/media/images/100x100/pdf reader/foxit-reader.jpg",
		To: "/categories/pdf-reader/foxit-reader",
		Categories: "PDF Reader",
		Windows: "Windows",
		Apps: "",
		desc:"Foxit Reader is a multilingual freemium PDF tool that can create, view, edit, digitally sign, and print PDF files.",
		olderversions: Nootherversion(),
		filename:"readerdc_en_ka_cra_goca_install",
		setupsize:"160MB",
		Free:"Free",
		dev:"Foxit",
		devhref:"https://www.foxit.com/",
		sysos:"Windows",
		sysram:" 2GB",
		type:"Offline Installer",
		sysarch:'×64',
		Download:<div><Downloadbtn to='https://cdn01.foxitsoftware.com/product/reader/desktop/win/11.0.0/FoxitReader110_enu_Setup_Prom.exe' className="mb-3" color="btn btn-primary" Version="Windows"/></div>
	},
	{
		Name: "Icecream PDF Reader",
		img: "/media/images/100x100/pdf reader/ice-cream-reader.jpg",
		To: "/categories/pdf-reader/ice-cream-reader",
		Categories: "PDF Reader",
		Windows: "Windows",
		Apps: "",
		desc:"Icecream Ebook Reader is a smart program for reading and organizing ebooks in different formats, including PDF.",
		olderversions: Nootherversion(),
		filename:"pdf_editor_setup.exe",
		setupsize:"160MB",
		Free:"Free",
		dev:"Icecream",
		devhref:"https://icecreamapps.com/PDF-Editor/",
		sysos:"Windows",
		sysram:" 2GB",
		type:"Offline Installer",
		sysarch:'×32 ×64',
		Download:<div><Downloadbtn to='https://download.icecreamapps.com/pdf_editor_setup.exe' className="mb-3" color="btn btn-primary" Version="Windows"/></div>
	},
	{
		Name: "Nitro PDF Reader",
		img: "/media/images/100x100/pdf reader/nitro.jpg",
		To: "/categories/pdf-reader/nitro-pdf-reader",
		Categories: "PDF Reader",
		Windows: "Windows",
		Apps: "",
		desc:"Nitro PDF Reader has a simple and basic user interface, and most importantly, it is free to download.",
		olderversions: Nootherversion(),
		filename:"nitro_pro13_ba_x64.msi for x64, nitro_pro13_ba_x86.msi for x32",
		setupsize:"250MB",
		Free:"Trial",
		dev:"Nitro",
		devhref:"https://www.gonitro.com/pdf-reader",
		sysos:"Windows",
		sysram:" 2GB",
		type:"Offline Installer",
		sysarch:'×32 ×64',
		Download:<div><Downloadbtn to='https://install.nitropdf.com/professional_13423855/en/retail/nitro_pro13_ba_x64.msi' className="mb-3" color="btn btn-primary" Version="Windows &times;64"/><Downloadbtn to='https://install.nitropdf.com/professional_13423855/en/retail/nitro_pro13_ba_x86.msi' className="mb-3" color="btn btn-primary" Version="Windows &times;32"/></div>
	},
	{
		Name: "PDF Elements",
		img: "/media/images/100x100/pdf reader/pdf-elements.jpg",
		To: "/categories/pdf-reader/pdf-elements",
		Categories: "PDF Reader",
		Windows: "Windows",
		Apps: "",
		desc:"Wondershare PDFelement is your all-in-one PDF solution. Create, edit, convert, annotate, protect, merge, watermark, compress, and sign PDF files in a better way.",
		olderversions: Nootherversion(),
		filename:"pdfelement-pro_setup_full5239.exe",
		setupsize:"1MB",
		Free:"Buy",
		dev:"WonderShare",
		devhref:"https://pdf.wondershare.com/",
		sysos:"Windows",
		sysram:" 4GB",
		type:"Online Installer",
		sysarch:'×64',
		Download:<div><Downloadbtn to='https://download.wondershare.com/inst/pdfelement-pro_setup_full5239.exe' className="mb-3" color="btn btn-primary" Version="Windows &times;64"/></div>
	},
	{
		Name: "PDF Xchange Reader",
		img: "/media/images/100x100/pdf reader/pdf-xchange-reader.jpg",
		To: "/categories/pdf-reader/pdf-xchange-reader",
		Categories: "PDF Reader",
		Windows: "Windows",
		Apps: "",
		desc:"PDF-XChange Viewer is a proprietary PDF reader for Microsoft Windows available for free. Its further development has been stopped in favour of freemium shareware PDF-Xchange Editor.",
		olderversions: Nootherversion(),
		filename:"PDFXVwer.zip",
		setupsize:"20MB",
		Free:"Free",
		dev:"Xchange Viewer",
		devhref:"https://www.tracker-software.com/product/pdf-xchange-viewer",
		sysos:"Windows",
		sysram:" 4GB",
		type:"Offline Installer",
		sysarch:'×32 ×64',
		Download:<div><Downloadbtn to='https://downloads.pdf-xchange.com/PDFXVwer.zip' className="mb-3" color="btn btn-primary" Version="Windows"/></div>
	},
	{
		Name: "Slim PDF Viewer",
		img: "/media/images/100x100/pdf reader/slim-pdf.jpg",
		To: "/categories/pdf-reader/slim-pdf",
		Categories: "PDF Reader",
		Windows: "Windows",
		Apps: "",
		desc:"The New and Improved Slim PDF Reader Experience new ways to view your PDF documents: An all-new user interface with light and dark theme support. Improved navigation for a simplified PDF viewing experience.",
		olderversions: Nootherversion(),
		filename:"InstallSlimPDFReader.exe",
		setupsize:"???",
		Free:"Free",
		dev:"Investintech",
		devhref:"https://www.investintech.com/support/desktop/slimpdfreader/",
		sysos:"Windows",
		sysram:" 4GB",
		type:"Offline Installer",
		sysarch:'×32 ×64',
		Download:<div><Downloadbtn to='https://cdn.investintech.com/download/InstallSlimPDFReader.exe' className="mb-3" color="btn btn-primary" Version="Windows"/></div>
	},
	{
		Name: "Sumantra PDF Reader",
		img: "/media/images/100x100/pdf reader/sumantra.jpg",
		To: "/categories/pdf-reader/sumantra",
		Categories: "PDF Reader",
		Windows: "Windows",
		Apps: "",
		desc:"The Sumatra PDF Viewer is a tiny open source portable reader that opens PDF's in the blink of an eye. Bloat. so we have a faster experience.",
		olderversions: Nootherversion(),
		filename:"SumatraPDF-3.1.2.zip",
		setupsize:"5MB",
		Free:"Free",
		dev:"Sumantra",
		devhref:"",
		sysos:"Windows",
		sysram:" 4GB",
		type:"Online Installer",
		sysarch:'×32 ×64',
		Download:<div><Downloadbtn to='https://slc.lo4d.com/files/sumatrapdf-portable/SumatraPDF-3.1.2.zip' className="mb-3" color="btn btn-primary" Version="Windows"/></div>
	},
	{
		Name: "JDK",
		img: "/media/images/100x100/programming/jdk.jpg",
		To: "/categories/programming/jdk",
		Categories: "Programming",
		Windows: "Windows",
		Apps: "",
		desc: "The JDK is an implementation of the Java platform specification, including compiler and class libraries.",
		olderversions: Nootherversion(),
		filename: "jdk-16.0.1_windows-x64_bin",
		setupsize: "160MB",
		Free: "Free",
		dev: "Oracle",
		devhref: "https://www.oracle.com/in/java/technologies/javase-downloads.html",
		sysos: "8.1, 10",
		sysram: "greater 4GB",
		type: "Offline Installer",
		sysarch: '×64',
		Download: <div><span className="mb-3"><Downloadbtn className="mb-3" to="https://download.oracle.com/otn-pub/java/jdk/16.0.1+9/7147401fd7354114ac51ef3e1328291f/jdk-16.0.1_windows-x64_bin.exe" color="btn btn-primary" Version="Windows &times;64" /></span></div>
	},
	{
		Name: "Kotlin",
		img: "/media/images/100x100/programming/kotlin.jpg",
		To: "/categories/programming/kotlin",
		Categories: "Programming",
		Windows: "Windows",
		Apps: "",
		desc: "Kotlin is a cross-platform, statically typed, general-purpose programming language with type inference. Kotlin is designed to interoperate fully with Java, and the JVM version of Kotlin's standard library depends on the Java Class Library, but type inference allows its syntax to be more concise.",
		olderversions: Nootherversion(),
		filename: " kotlin-native-windows-1.5.20.zip",
		setupsize: "100MB",
		Free: "Free",
		dev: "Kotlin",
		devhref: "https://kotlinlang.org/",
		sysos: "8.1, 10",
		sysram: "greater 4GB",
		type: "Offline Installer",
		sysarch: '×64',
		Download: <div><span className="mb-3"><Downloadbtn className="mb-3" to="https://github.com/JetBrains/kotlin/releases/download/v1.5.20/kotlin-native-windows-1.5.20.zip" color="btn btn-primary" Version="Windows &times;64" /></span></div>
	},
	{
		Name: "Mamp",
		img: "/media/images/100x100/programming/mamp.jpg",
		To: "/categories/programming/mamp",
		Categories: "Programming",
		Windows: "Windows",
		Apps: "",
		desc: "MAMP is a free, local server environment that can be installed under macOS and Windows with just a few clicks. MAMP provides them with all the tools they need to run WordPress on their desktop PC for testing or development purposes.",
		olderversions: Nootherversion(),
		filename: " kotlin-native-windows-1.5.20.zip",
		setupsize: "458MB",
		Free: "???",
		dev: "MAMP",
		devhref: "https://www.mamp.info/en/windows/",
		sysos: "8.1, 10",
		sysram: "greater 4GB",
		type: "Offline Installer",
		sysarch: '×64',
		Download: <div><span className="mb-3"><Downloadbtn className="mb-3" to="https://www.mamp.info/en/downloads/" color="btn btn-primary" Version="Windows &times;64" /></span></div>
	},
	{
		Name: "Matlab",
		img: "/media/images/100x100/programming/matlab.jpg",
		To: "/categories/programming/matlab",
		Categories: "Programming",
		Windows: "Windows",
		Apps: "",
		desc: "MATLAB stands for Matrix Laboratory. It is a high-performance language that is used for technical computing. It was developed by Cleve Molar of the company MathWorks.Inc in the year 1984.",
		olderversions: Nootherversion(),
		filename: " Matlab",
		setupsize: "???",
		Free: "Buy",
		dev: "Matlab",
		devhref: "https://www.mathworks.com/products/matlab.html",
		sysos: "8.1, 10",
		sysram: "greater 4GB",
		type: "Offline Installer",
		sysarch: '×64',
		Download: <div><span className="mb-3"><Downloadbtn className="mb-3" to="https://www.mathworks.com/products/matlab.html" color="btn btn-primary" Version="Windows &times;64" /></span></div>
	},
	{
		Name: "Mingw w64",
		img: "/media/images/100x100/programming/mingw-w64.jpg",
		To: "/categories/programming/mingw-w64",
		Categories: "Programming",
		Windows: "Windows",
		Apps: "",
		desc: "Mingw-w64 is a free and open source software development environment to create Microsoft Windows PE applications. It was forked in 2005–2008 from MinGW (Minimalist GNU for Windows).",
		olderversions: Nootherversion(),
		filename: " mingw-w64",
		setupsize: "15MB",
		Free: "Free",
		dev: "Mingw-w64",
		devhref: "http://mingw-w64.org/doku.php",
		sysos: "7, 8, 8.1, 10",
		sysram: "greater 4GB",
		type: "Offline Installer",
		sysarch: '×32 ×64',
		Download: <div><span className="mb-3"><Downloadbtn className="mb-3" to="https://sourceforge.net/projects/mingw-w64/files/mingw-w64/mingw-w64-release/" color="btn btn-primary" Version="Windows" /></span></div>
	},
	{
		Name: "Python",
		img: "/media/images/100x100/programming/python.jpg",
		To: "/categories/programming/python",
		Categories: "Programming",
		Windows: "Windows",
		Apps: "",
		desc:"Python is a widely used general-purpose, high level programming language. It was created by Guido van Rossum in 1991 and further developed by the Python Software Foundation.",
		olderversions: Nootherversion(),
		filename: " pythonv-3.9",
		setupsize: "30MB",
		Free: "Free",
		dev: "Python",
		devhref: "https://www.python.org/",
		sysos: "7, 8, 8.1, 10",
		sysram: "greater than 2GB",
		type: "Offline Installer",
		sysarch: '×32 ×64',
		Download: <div><span className="mb-3"><Downloadbtn className="mb-3" to="https://www.python.org/ftp/python/3.9.6/python-3.9.6.exe" color="btn btn-primary" Version="Windows &times;32" /><Downloadbtn className="mb-3" to="https://www.python.org/ftp/python/3.9.6/python-3.9.6-amd64.exe" color="btn btn-primary" Version="Windows &times;64" /></span></div>
	},
	{
		Name: "Q Basic",
		img: "/media/images/100x100/programming/q-basic.jpg",
		To: "/categories/programming/q-basic",
		Categories: "Programming",
		Windows: "Windows",
		Apps: "",
		desc:"QBasic is an integrated development environment (IDE) and interpreter for a variety of dialects of BASIC which are based on QuickBASIC.Code entered into the IDE is compiled to an intermediate representation (IR).",
		olderversions: Nootherversion(),
		filename: " BASIC2DOSBox",
		setupsize: "15MB",
		Free: "Free",
		dev: "QBasic",
		devhref: "https://www.qbasic.net/",
		sysos: "7, 8, 8.1, 10",
		sysram: "greater than 2GB",
		type: "Offline Installer",
		sysarch: '×32 ×64',
		Download: <div><span className="mb-3"><Downloadbtn className="mb-3" to="https://www.qbasic.net/dl.php?id=SG1U8Ji02j6Cs&amp;file=qbdbox" color="btn btn-primary" Version="Windows" /></span></div>
	},
	{
		Name: "R",
		img: "/media/images/100x100/programming/r.jpg",
		To: "/categories/programming/r",
		Categories: "Programming",
		Windows: "Windows",
		Apps: "",
		desc:"R is a language and environment for statistical computing and graphics.",
		olderversions: Nootherversion(),
		filename: " R-4.1.0-win.exe",
		setupsize: "86MB",
		Free: "Free",
		dev: "R",
		devhref: "https://www.r-project.org/",
		sysos: "7, 8, 8.1, 10",
		sysram: "greater than 2GB",
		type: "Offline Installer",
		sysarch: '×32 ×64',
		Download: <div><span className="mb-3"><Downloadbtn className="mb-3" to="https://mirror.niser.ac.in/cran/bin/windows/base/R-4.1.0-win.exe" color="btn btn-primary" Version="Windows" /></span></div>
	},
	{
		Name: "Ruby",
		img: "/media/images/100x100/programming/ruby.jpg",
		To: "/categories/programming/ruby",
		Categories: "Programming",
		Windows: "Windows",
		Apps: "",
		desc:"Ruby is a dynamic, open source programming language with a focus on simplicity and productivity. It has an elegant syntax that is natural to read and easy to write.",
		olderversions: Nootherversion(),
		filename: " R-4.1.0-win.exe",
		setupsize: "20MB",
		Free: "Free",
		dev: "Ruby",
		devhref: "https://www.ruby-lang.org/en/downloads/",
		sysos: "7, 8, 8.1, 10",
		sysram: "greater than 2GB",
		type: "Offline Installer",
		sysarch: '×32 ×64',
		Download: <div><span className="mb-3"><Downloadbtn className="mb-3" to="https://cache.ruby-lang.org/pub/ruby/3.0/ruby-3.0.2.tar.gz" color="btn btn-primary" Version="Windows" /></span></div>
	},
	{
		Name: "Scratch 1",
		img: "/media/images/100x100/programming/scratch-1.jpg",
		To: "/categories/programming/scratch-1",
		Categories: "Programming",
		Windows: "Windows",
		Apps: "",
		desc:"Scratch is a free programming language developed by MIT that makes it easy to create interactive stories, animations, games, music, and art, and share your creations on the web. And this is the First Version of Scratch (Scratch v1)",
		olderversions: Nootherversion(),
		filename: " ScratchInstaller1.4",
		setupsize: "34MB",
		Free: "Free",
		dev: "Scratch",
		devhref: "https://scratch.mit.edu/scratch_1.4",
		sysos: "7, 8, 8.1, 10",
		sysram: "greater than 2GB",
		type: "Offline Installer",
		sysarch: '×32 ×64',
		Download: <div><span className="mb-3"><Downloadbtn className="mb-3" to="https://download.scratch.mit.edu/ScratchInstaller1.4.exe" color="btn btn-primary" Version="Windows" /></span></div>
	},
	{
		Name: "Scratch 2",
		img: "/media/images/100x100/programming/scratch-2.jpg",
		To: "/categories/programming/scratch-2",
		Categories: "Programming",
		Windows: "Windows",
		Apps: "",
		desc:"Scratch is a free programming language developed by MIT that makes it easy to create interactive stories, animations, games, music, and art, and share your creations on the web. And this is the Second Version of Scratch (Scratch v3)",
		olderversions: Nootherversion(),
		filename: " Scratch_461",
		setupsize: "59MB",
		Free: "Free",
		dev: "Scratch",
		devhref: "https://scratch.mit.edu/download/scratch2",
		sysos: "7, 8, 8.1, 10",
		sysram: "greater than 2GB",
		type: "Offline Installer",
		sysarch: '×32 ×64',
		Download: <div><span className="mb-3"><Downloadbtn className="mb-3" to="https://download.scratch.mit.edu/scratch2download/sa/Scratch-461.exe" color="btn btn-primary" Version="Windows" /><br /><span><b>Note : Scratch 2 has a dependency on Adobe AIR. You can <a href="https://get-softwares.github.io/adobeair/AdobeAIR.exe">Download it</a></b></span></span></div>
	},
	{
		Name: "Scratch 3",
		img: "/media/images/100x100/programming/scratch-3.jpg",
		To: "/categories/programming/scratch-3",
		Categories: "Programming",
		Windows: "Windows",
		Apps: "",
		desc:"Scratch is a free programming language developed by MIT that makes it easy to create interactive stories, animations, games, music, and art, and share your creations on the web. And this is the Latest Version of Scratch (Scratch v3)",
		olderversions: Nootherversion(),
		filename: " Scratch_3",
		setupsize: "130MB",
		Free: "Free",
		dev: "Scratch",
		devhref: "https://scratch.mit.edu/download",
		sysos: "10",
		sysram: "greater than 2GB",
		type: "Offline Installer",
		sysarch: '×32 ×64',
		Download: <div><span className="mb-3"><Downloadbtn className="mb-3" to="https://downloads.scratch.mit.edu/desktop/Scratch%20Setup.exe" color="btn btn-primary" Version="Windows" /></span></div>
	},
	{
		Name: "Wamp Server",
		img: "/media/images/100x100/programming/wamp.png",
		To: "/categories/programming/wamp",
		Categories: "Programming",
		Windows: "Windows",
		Apps: "",
		desc:"Wamp Server is a Windows web development environment. It allows you to create web applications with Apache2, PHP and a MySQL database. Alongside, PhpMyAdmin allows you to manage easily your databases.",
		olderversions: Nootherversion(),
		filename: " wampserver3.2.3_x64 for x64, wampserver3.2.3_x32 for x32",
		setupsize: "350MB for x86, 450MB for x64",
		Free: "Free",
		dev: "Wamp",
		devhref: "https://www.wampserver.com/",
		sysos: "7, 8.1, 10",
		sysram: "greater than 3GB",
		type: "Offline Installer",
		sysarch: '×32 ×64',
		Download: <div><span className="mb-3"><Downloadbtn className="mb-3" to="https://slc.lo4d.com/files/wampserver/wampserver3.2.3_x86.exe" color="btn btn-primary" Version="Windows &times;32" /><Downloadbtn className="mb-3" to="https://lon-01.lo4d.com/files/wampserver/wampserver3.2.3_x64.exe" color="btn btn-primary" Version="Windows &times;64" /></span></div>
	},
	{
		Name: "Xampp",
		img: "/media/images/100x100/programming/xampp.jpg",
		To: "/categories/programming/xampp",
		Categories: "Programming",
		Windows: "Windows",
		Apps: "",
		desc:"XAMPP is a free and open-source cross-platform web server solution stack package developed by Apache Friends, consisting mainly of the Apache HTTP Server, MariaDB database, and interpreters for scripts written in the PHP and Perl programming languages.",
		olderversions: Nootherversion(),
		filename: " xampp-windows-x64-8.0.8-0-VS16-installer.exe",
		setupsize: "160MB",
		Free: "Free",
		dev: "Apache",
		devhref: "https://www.apachefriends.org/download.html",
		sysos: "7, 8.1, 10",
		sysram: "greater than 4GB",
		type: "Offline Installer",
		sysarch: '×64',
		Download: <div><span className="mb-3"><Downloadbtn className="mb-3" to="https://www.apachefriends.org/xampp-files/8.0.8/xampp-windows-x64-8.0.8-0-VS16-installer.exe" color="btn btn-primary" Version="Windows &times;64" /></span></div>
	},
	// {
	// 	Name: "Active Representer",
	// 	img: "/media/images/100x100/screen-recording/activepresenter.jpg",
	// 	To: "/categories/screen-recording/active-representer",
	// 	Categories: "Screen Recording",
	// 	Windows: "Windows",
	// 	Apps: "",
	// 	desc:"ActivePresenter is a free screen recorder and screencast video editor with all the necessary editing tools for recording screen & creating engaging screencast videos on Windows and macOS.",
	// 	olderversions:"",
	// 	Download:"",
	// },
	// {
	// 	Name: "Bandicam",
	// 	img: "/media/images/100x100/screen-recording/bandicam.jpg",
	// 	To: "/categories/screen-recording/bandicam",
	// 	Categories: "Screen Recording",
	// 	Windows: "Windows",
	// 	Apps: "",
	// 	desc:"Bandicam is a screen capture and screen recording utility originally developed by Bandisoft and later by Bandicam Company that can take screenshots or record screen changes.",
	// 	olderversions:"",
	// 	Download:"",
	// },
	// {
	// 	Name: "Cam Studio",
	// 	img: "/media/images/100x100/screen-recording/camstudio.jpg",
	// 	To: "/categories/screen-recording/cam-studio",
	// 	Categories: "Screen Recording",
	// 	Windows: "Windows",
	// 	Apps: "",
	// 	desc:"CamStudio is an open-source screencasting program for Microsoft Windows released as free software. The software renders videos in an AVI format.",
	// 	olderversions:"",
	// 	Download:"",
	// },
	// {
	// 	Name: "Debut",
	// 	img: "/media/images/100x100/screen-recording/debut.jpg",
	// 	To: "/categories/screen-recording/debut",
	// 	Categories: "Screen Recording",
	// 	Windows: "Windows",
	// 	Apps: "",
	// 	desc:"Debut is a video capture and screencast program from NCH Software, available for both Windows and Mac. It has two versions, Professional and Home. In order to provide users with additional capabilities often required for video editing and presentation.",
	// 	olderversions:"",
	// 	Download:"",
	// },
	// {
	// 	Name: "Flashback",
	// 	img: "/media/images/100x100/screen-recording/flashback.jpg",
	// 	To: "/categories/screen-recording/flashback",
	// 	Categories: "Screen Recording",
	// 	Windows: "Windows",
	// 	Apps: "",
	// 	desc:"FlashBack is a Windows-based screen recording program, distributed by Blueberry Software. It allows the user to add text effects, cut and paste movie footage and edit mouse movements.",
	// 	olderversions:"",
	// 	Download:"",
	// },
	// {
	// 	Name: "Fraps",
	// 	img: "/media/images/100x100/screen-recording/fraps.jpg",
	// 	To: "/categories/screen-recording/fraps",
	// 	Categories: "Screen Recording",
	// 	Windows: "Windows",
	// 	Apps: "",
	// 	desc:"Fraps is a benchmarking, screen capture and screen recording utility for Windows developed by Beepa. It can capture from software that uses DirectX and OpenGL, such as PC games.",
	// 	olderversions:"",
	// 	Download:"",
	// },
	// {
	// 	Name: "Loilo Recorder",
	// 	img: "/media/images/100x100/screen-recording/loilo-game-recorder.jpg",
	// 	To: "/categories/screen-recording/loilo-recorder",
	// 	Categories: "Screen Recording",
	// 	Windows: "Windows",
	// 	Apps: "",
	// 	desc:"The LoiLo Game Recorder is a very simple and easy to use recorder that is totally free. So whenever you want to start recording the screen, you are only required to open the selected game, press the record button and all done.",
	// 	olderversions:"",
	// 	Download:"",
	// },
	// {
	// 	Name: "OBS Studio",
	// 	img: "/media/images/100x100/screen-recording/obs.jpg",
	// 	To: "/categories/screen-recording/obs-studio",
	// 	Categories: "Screen Recording",
	// 	Windows: "Windows",
	// 	Apps: "",
	// 	desc:"Open Broadcaster Software (OBS) is a free and open-source cross-platform streaming and recording program built with Qt and maintained by the OBS Project. Since 2016,",
	// 	olderversions:"",
	// 	Download:"",
	// },
	// {
	// 	Name: "Screencast Matic",
	// 	img: "/media/images/100x100/screen-recording/screencast-matic.jpg",
	// 	To: "/categories/screen-recording/screencast-matic",
	// 	Categories: "Screen Recording",
	// 	Windows: "Windows",
	// 	Apps: "",
	// 	desc:"Screencast Matic is used to record your screen. You can capture any area of your screen for quick recordings with the option to add audio narration from your microphone and video from your webcam.",
	// 	olderversions:"",
	// 	Download:"",
	// },
	// {
	// 	Name: "XSplit",
	// 	img: "/media/images/100x100/screen-recording/xsplit.jpg",
	// 	To: "/categories/screen-recording/xsplit",
	// 	Categories: "Screen Recording",
	// 	Windows: "Windows",
	// 	Apps: "",
	// 	desc:"XSplit is so much more than a screen recorder, it is a fully featured production studio packed into one broadcasting app. The biggest names in esports, conferences and conventions rely on XSplit to stream their events globally.",
	// 	olderversions:"",
	// 	Download:"",
	// },
];

export default Data;